Repository aws-amplify/docs, pull requests merged in 2019-03, with the labels that each got.

#432 Add section for Cognito Hosted UI on React Native
  .spelling
  js/authentication.md
Labels: JavaScript

#507 add AppComponent class
  js/angular.md
Labels: JavaScript, needs-discussion

#455 Added missing exceptions
  js/authentication.md
Labels: JavaScript

#423 Update authentication.md
  js/authentication.md
Labels: JavaScript

#490 Be explicit about data types for atts and metrics
  js/analytics.md
Labels: JavaScript

#464 Updated jwtToken fetch syntax
  js/api.md
Labels: JavaScript

#518 Fix doc typo
  js/api.md
Labels: JavaScript

#517 Alpn update
  ios/pubsub.md
Labels: Android

#514 Add Hosting option with AWS Amplify Console
  cli/hosting.md
  images/.DS_Store
Labels: CLI

#388 Remove "graphqlOperation" import from REST API documentation
  js/react.md
Labels: JavaScript

#365 auth doc enhance
  js/authentication.md
Labels: JavaScript

#435 Change Authenticator override documentation
  js/authentication.md
Labels: JavaScript

#529 Update js/analytics.md
  js/analytics.md
Labels: JavaScript

#439 Specify auth steps for React Native
  js/react.md
Labels: JavaScript

#487 Added missing import for buildMutation
  js/api.md
Labels: JavaScript

#442 Update init.md
  cli/init.md
Labels: CLI

#426 Update instructions to capture new features of AWSMobileClient
  .spelling
  android/authentication.md
  android/media/dev-auth-ids-console-settings.png
  ios/authentication.md
  ios/images/dev-auth-ids-console-settings.png
Labels: Android, iOS, pending release

#542 Update android/storage.md
  .spelling
  android/storage.md
Labels: Android

#553 Update start.md
  ios/start.md
Labels: iOS

#470 Update documentation on graphQL transform
  cli/graphql.md
Labels: CLI

#548 Fix typo in Storage put code
  js/storage.md
Labels: JavaScript

#528 Tutorial code change for Ionic 4.
  js/tutorials/building-ionic-4-apps/index.md
Labels: JavaScript

#544 Docs for new Hub refactor
  js/hub.md
Labels: JavaScript

#537 Improve the doc for federated identities
  js/authentication.md
Labels: JavaScript
