Repository aws-amplify/docs, pull requests merged in 2019-07, with the labels that each got.

#772 [API] Update build.gradle to highlight dependencies
  android/api.md
Labels: Android

#783 Update Android Push Notification docs to handle "Open your app" action
  android/push-notifications-handle-fcm.md
Labels: Android

#740 Add more description about onRegister
  js/push-notifications.md
Labels: JavaScript

#748 Fix Vue example: remove trailing comma
  js/vue.md
Labels: JavaScript

#749 Use html highlighting for Vue SFC code
  js/vue.md
Labels: JavaScript

#758 Typo error [info.identityId]
  js/pubsub.md
Labels: JavaScript

#759 Add import example for graphqlOperation
  js/api.md
Labels: JavaScript

#775 [iOS][Auth] Minor formatting changes
  ios/authentication.md
Labels: iOS

#781 Update Analytics docs to add integration with Auth
  android/analytics.md
  ios/analytics.md
Labels: Android, iOS

#787 documentation: update api.md accessToken api references
  js/api.md
Labels: JavaScript

#789 Update iOS docs to 2.10.0
  ios/analytics.md
  ios/api.md
  ios/authentication.md
  ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md
  ios/pubsub.md
  ios/push-notifications.md
  ios/start.md
  ios/storage.md
Labels: iOS

#785 Getting started js
  .spelling
  js/start.md
Labels: JavaScript, feature-request

#770 Update OAuth documentation to explain custom state option
  js/authentication.md
Labels: JavaScript, pending-library-publish

#816 Update authentication.md
  android/authentication.md
Labels: Android
