Repository aws-amplify/docs, pull requests merged in 2019-06, with the labels that each got.

#714 [Android][iOS] Clarify IAM policy update step
  android/analytics.md
  ios/analytics.md
Labels: Android, iOS

#453 Allowing Cognito Auth Role to access IoT Services
  js/pubsub.md
Labels: JavaScript

#605 Fix for topnav misalignment
  theme/_sass/components/_redesign.scss
Labels: documentation site

#700 Update SMS section of messaging.md
  android/messaging.md
Labels: Android

#709 Add link to attributes list for cognito user pools
  js/authentication.md
Labels: JavaScript

#708 Document outdated, updating with the actual value
  theme/_includes/sign-up-attributes.html
Labels: JavaScript

#643 Add JS documentation for PushNotification.requestIOSPermissions
  js/push-notifications.md
Labels: JavaScript

#571 Corrected graphql.md
  cli/graphql.md
Labels: CLI

#614 Add documentation block on filtering subscriptions
  cli/graphql.md
Labels: CLI

#634 add "subscriptions" on @model SDL
  cli/graphql.md
Labels: CLI

#707 Add try catch block around onCreate.
  js/api.md
Labels: JavaScript

#694 chore: update parity for all frameworks on naming conventions
  js/analytics.md
  js/angular.md
  js/api.md
  js/authentication.md
  js/interactions.md
  js/react.md
  js/start.md
  js/storage.md
  js/vue.md
  js/xr.md
Labels: JavaScript

#580 Adding more info about refreshing JWT tokens
  js/authentication.md
Labels: JavaScript

#725 Update getting started for iOS
  ios/start.md
Labels: iOS

#717 Add note about JWT storage
  js/react.md
Labels: JavaScript

#727 [Analytics] Update docs with service limits
  android/analytics.md
  ios/analytics.md
Labels: Android, iOS

#716 Updates react-native image upload example
  js/storage.md
Labels: JavaScript

#733 Added a SwiftUI callout
  .spelling
  ios/api.md
Labels: iOS

#574 Add Amazon Personalize Provider
  .spelling
  js/analytics.md
Labels: JavaScript

#622 Adding doc for signing up with email or phone number
  .spelling
  js/angular.md
  js/react.md
  js/vue.md
Labels: JavaScript

#747 Added note on changing graphql connections
  .spelling
  cli/graphql.md
Labels: CLI
