Repository aws-amplify/docs, pull requests merged in 2019-05, with the labels that each got.

#658 Update analytics.md
  ios/analytics.md
Labels: iOS

#659 [iOS] Clarify manual setup with AWSMobileClient
  ios/manualsetup.md
Labels: iOS

#660 [iOS][Android] Update Pinpoint Analytics docs to include the required IAM policy
  android/analytics.md
  ios/analytics.md
Labels: Android, bug, iOS

#661 [iOS] Fix formatting in graphql complex objects
  ios/storage.md
Labels: bug, iOS

#654 Add documentation for hiding authenticator components
  js/angular.md
Labels: JavaScript

#638 adding new option to getPreferredMFA
  js/authentication.md
Labels: JavaScript

#667 Fix grammar in start.md
  js/start.md
Labels: bug

#612 Fix warnings thrown by react from App.js
  js/start.md
Labels: JavaScript

#362 Document responseType
  .spelling
  js/api.md
Labels: JavaScript

#673 Fix assignment in Storage documentation example code
  js/storage.md
Labels: JavaScript, bug

#572 update analytics docs: show how to fix the maximum endpoints error
  js/analytics.md
Labels: JavaScript

#672 [API] [GraphQL] Support Multiple Authorization modes for AWSAppSyncClient
  android/api.md
  ios/api.md
Labels: Android, iOS

#679 Update analytics.md to add missing `}`
  js/analytics.md
Labels: bug

#676 Remove unnecessary AWSCore import
  ios/analytics.md
Labels: iOS

#663 Adding example code for customized storage object of Auth
  js/authentication.md
Labels: JavaScript

#539 Update start.md
  js/start.md
Labels: CLI

#640 Adding @function directive docs
  .spelling
  cli/graphql.md
  package-lock.json
  yarn.lock
Labels: CLI

#696 Remove extra space in URL
  js/start.md
Labels: JavaScript, pending release

#701 Fix typo in Android API documentation
  android/api.md
Labels: Android, pending release

#690 Add missing '}' in code snippet
  ios/start.md
Labels: iOS

#705 [iOS][API] Fix Multi-Auth sample code snippet
  ios/api.md
Labels: iOS
