Repository aws-amplify/docs, pull requests merged in 2019-11, with the labels that each got.

#984 Update Getting Started guides for iOS and Android
  android/start.md
  ios/start.md
Labels: iOS

#1004 Clean up SDK list
  .spelling
  ios/manualsetup.md
Labels: iOS

#1007 feat(auth): Add optional oauth config to Manual Setup
  js/authentication.md
Labels: JavaScript

#1016 chore:(Getting Started - React) update code snippets and full sample code for react getting started
  js/start.md
Labels: JavaScript

#1015 fix typo in Authentication OAuth and HostedUI
  js/authentication.md
Labels: JavaScript, needs-review

#1014 Unify using the AWS Amplify plugin statement
  js/vue.md
Labels: JavaScript, needs-review

#907 Docs for amplify pull and multiple frontends
  cli-toolchain/images/multiple-frontends.png
  cli-toolchain/quickstart.md
Labels: CLI
