Repository aws-amplify/docs, pull requests merged in 2020-04, with the labels that each got.

#1402 chore: Update iOS Predictions
  docs/lib/predictions/fragments/ios/getting-started.md
Labels: v2

#1350 Updated auth docs, fixed broken UI Component example
  docs/lib/auth/fragments/js/emailpassword.md
  docs/start/getting-started/fragments/ionic/nextsteps.md
  docs/start/getting-started/fragments/react/nextsteps.md
  docs/start/getting-started/fragments/reactnative/nextsteps.md
  docs/start/getting-started/fragments/vue/nextsteps.md
  docs/ui/auth/fragments/react/usage.md
Labels: v2

#1406 Fixed installation instructions for expo
  docs/start/getting-started/fragments/reactnative/setup.md
Labels: v2

#1398 chore: re-enable indexing
  client/src/index.html
  client/src/robots.txt
  client/stencil.config.ts
Labels: v2

#1412 Updated JS datastore getting started
  docs/lib/datastore/fragments/js/data-access.md
  docs/lib/datastore/fragments/js/getting-started.md
  docs/lib/datastore/menu.json
  docs/lib/datastore/overview.md
Labels: v2

#1353 Remove switch subtitle from UI Components section
  client/src/docs-ui/menu/menu.tsx
Labels: v2

#1411 Addressing Auth JS feedback from daily review
  docs/lib/auth/emailpassword.md
  docs/lib/auth/fragments/js/advanced.md
  docs/lib/auth/fragments/js/emailpassword.md
  docs/lib/auth/fragments/js/getting-started.md
  docs/lib/auth/fragments/js/manageusers.md
  docs/lib/auth/fragments/js/mfa.md
  docs/lib/auth/fragments/js/social2.md
  docs/lib/auth/fragments/js/start.md
  docs/lib/auth/menu.json
  docs/lib/auth/social.md
  docs/lib/auth/social2.md
Labels: v2

#1386 Update to UI Components structure for Authenticator
  client/src/amplify-ui/toc/toc-content/toc-content.tsx
  client/src/amplify-ui/toc/toc-provider/toc-provider.tsx
  client/src/amplify-ui/toc/toc/toc.tsx
  client/src/components.d.ts
  client/src/docs-ui/page/__snapshots__/page.spec.ts.snap
  client/src/docs-ui/page/page.style.ts
  client/src/docs-ui/ui-component-props/__snapshots__/ui-component-props.spec.ts.snap
  client/src/docs-ui/ui-component-props/ui-component-props.spec.ts
  client/src/docs-ui/ui-component-props/ui-component-props.style.ts
  client/src/docs-ui/ui-component-props/ui-component-props.tsx
  client/src/utils/heading-is-visible.ts
  docs/ui/auth/authenticator.md
  docs/ui/auth/confirm-sign-in.md
  docs/ui/auth/confirm-sign-up.md
  docs/ui/auth/forgot-password.md
  docs/ui/auth/fragments/angular/authenticator.md
  docs/ui/auth/fragments/angular/sign-out.md
  docs/ui/auth/fragments/angular/usage.md
  docs/ui/auth/fragments/ionic/authenticator.md
  docs/ui/auth/fragments/ionic/sign-out.md
  docs/ui/auth/fragments/react-native/authenticator.md
  docs/ui/auth/fragments/react/authenticator.md
  docs/ui/auth/fragments/react/sign-out.md
  docs/ui/auth/fragments/react/usage.md
  docs/ui/auth/fragments/vue/authenticator.md
  docs/ui/auth/fragments/vue/sign-out.md
  docs/ui/auth/fragments/vue/usage.md
  docs/ui/auth/greetings.md
  docs/ui/auth/menu.json
  docs/ui/auth/require-new-password.md
  docs/ui/auth/sign-in.md
  docs/ui/auth/sign-out.md
  docs/ui/auth/sign-up.md
  docs/ui/auth/totp-setup.md
  docs/ui/auth/verify-contact.md
  docs/ui/customization/fragments/react-native/theming.md
  docs/ui/customization/fragments/web/theming.md
  docs/ui/customization/menu.json
  docs/ui/customization/slots.md
  docs/ui/customization/theming.md
  docs/ui/fragments/angular/installation.md
  docs/ui/fragments/ionic/installation.md
  docs/ui/fragments/react-native/installation.md
  docs/ui/fragments/react-native/not-supported.md
  docs/ui/fragments/react/installation.md
  docs/ui/fragments/vue/installation.md
  docs/ui/ui.md
  package.json
  yarn.lock
Labels: v2

#1388 fix: filter state linking behavior
  client/src/docs-ui/page/page.tsx
Labels: v2

#1357 readme usernameAlias auth
  docs/ui/auth/fragments/angular/authenticator.md
  docs/ui/auth/fragments/ionic/authenticator.md
  docs/ui/auth/fragments/react/authenticator.md
  docs/ui/auth/fragments/vue/authenticator.md
Labels: v2

#1418 fix: hash link bug
  capi/src/visitors/links.ts
  client/src/docs-ui/in-page-link/in-page-link.tsx
  client/src/docs-ui/page/page.tsx
  client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap
  client/src/docs-ui/secondary-nav/secondary-nav.tsx
  client/src/utils/get-element-top.ts
  client/src/utils/get-nav-height.ts
  client/src/utils/scroll-to-hash.ts
  report.20200402.163208.58061.0.001.json
Labels: v2

#1431 fix: prevent incorrect nav height under certain conditions
  client/src/docs-ui/page/page.tsx
Labels: v2

#1432 Custom attributes, auth polish, lambda trigger updates.
  docs/lib/auth/fragments/js/advanced.md
  docs/lib/auth/fragments/js/emailpassword.md
Labels: v2

#1373 Fixes for Android Auth SDK Overview
  docs/sdk/auth/drop-in-auth.md
  docs/sdk/auth/fragments/android/custom-auth-flow.md
  docs/sdk/auth/fragments/android/federated-identities.md
  docs/sdk/auth/fragments/android/getting-started.md
  docs/sdk/auth/fragments/android/guest-access.md
  docs/sdk/auth/fragments/android/how-it-works.md
  docs/sdk/auth/guest-access.md
  docs/sdk/auth/menu.json
  docs/sdk/auth/working-with-api.md
Labels: v2

#1444 Properly stylize DataStore in the left navigation
  docs/lib/datastore/getting-started.md
  docs/lib/datastore/menu.json
Labels: v2

#1395 Added documentation for Lambda cron jobs and additional runtime support
  docs/cli/function/function.md
  docs/cli/usage/iam.md
Labels: v2

#1363 Update iOS SDK - Storage and Auth
  docs/sdk/auth/fragments/ios/custom-auth-flow.md
  docs/sdk/auth/fragments/ios/device-features.md
  docs/sdk/auth/fragments/ios/drop-in-auth.md
  docs/sdk/auth/fragments/ios/federated-identities.md
  docs/sdk/auth/fragments/ios/getting-started.md
  docs/sdk/auth/fragments/ios/guest-access.md
  docs/sdk/auth/fragments/ios/hosted-ui.md
  docs/sdk/auth/fragments/ios/how-it-works.md
  docs/sdk/auth/fragments/ios/working-with-api.md
  docs/sdk/auth/getting-started.md
  docs/sdk/storage/fragments/ios/configure-access.md
  docs/sdk/storage/fragments/ios/getting-started.md
  docs/sdk/storage/fragments/ios/graphql-api.md
  docs/sdk/storage/fragments/ios/transfer-utility.md
  docs/start/getting-started/fragments/ios/setup.md
Labels: v2

#1400 chore: update API for SDK and API+DataStore for Amplify WIP
  docs/lib/datastore/fragments/ios/getting-started.md
  docs/lib/datastore/fragments/ios/relational.md
  docs/lib/datastore/fragments/ios/sync.md
  docs/lib/getting-started/fragments/ios/generate-model.md
  docs/lib/getting-started/fragments/ios/setup.md
  docs/lib/graphqlapi/fragments/ios/authz.md
  docs/lib/graphqlapi/fragments/ios/getting-started.md
  docs/lib/restapi/fragments/ios/getting-started.md
  docs/sdk/api/fragments/ios/graphql.md
  docs/sdk/api/fragments/ios/rest.md
Labels: v2

#1356 Fix incorrect code syntax in angular docs
  docs/start/getting-started/fragments/angular/data-model.md
Labels: v2

#1455 Align Federated Identities section with iOS
  docs/images/new-facebook-add-platform.png
  docs/images/new-facebook-add-testers.png
  docs/images/new-facebook-app-id.png
  docs/images/new-facebook-app-new-app-id.png
  docs/images/new-facebook-app.png
  docs/sdk/auth/fragments/android/federated-identities.md
Labels: v2

#1459 large updates to JavScript Library GraphQL API category docmentation
  docs/cli/function/function.md
  docs/lib/graphqlapi/advanced-workflows.md
  docs/lib/graphqlapi/concepts.md
  docs/lib/graphqlapi/create-or-re-use-existing-backend.md
  docs/lib/graphqlapi/fragments/graphql-from-node.md
  docs/lib/graphqlapi/fragments/js/authz.md
  docs/lib/graphqlapi/fragments/js/create-or-re-use-existing-backend.md
  docs/lib/graphqlapi/fragments/js/delta-sync.md
  docs/lib/graphqlapi/fragments/js/getting-started.md
  docs/lib/graphqlapi/fragments/js/mutate-data.md
  docs/lib/graphqlapi/fragments/js/offline.md
  docs/lib/graphqlapi/fragments/js/query-data.md
  docs/lib/graphqlapi/graphql-from-nodejs.md
  docs/lib/graphqlapi/menu.json
  docs/lib/graphqlapi/mutate-data.md
  docs/lib/graphqlapi/overview.md
Labels: v2

#1453 Add SDK Setup Options
  docs/sdk/auth/fragments/android/how-it-works.md
  docs/sdk/auth/fragments/ios/how-it-works.md
  docs/sdk/configuration/fragments/android/setup-options.md
  docs/sdk/configuration/fragments/ios/setup-options.md
  docs/sdk/configuration/menu.json
  docs/sdk/configuration/setup-options.md
  docs/sdk/menu.json
  docs/start/getting-started/fragments/android/nextsteps.md
  docs/start/getting-started/fragments/ios/nextsteps.md
Labels: v2

#1405 Migrate legacy UI components content
  docs/ui-legacy/api/connect.md
  docs/ui-legacy/api/fragments/react/connect.md
  docs/ui-legacy/api/fragments/vue/connect.md
  docs/ui-legacy/api/menu.json
  docs/ui-legacy/api/overview.md
  docs/ui-legacy/auth/authenticator.md
  docs/ui-legacy/auth/fragments/angular/authenticator.md
  docs/ui-legacy/auth/fragments/react/authenticator.md
  docs/ui-legacy/auth/fragments/react/sign-up-attributes.md
  docs/ui-legacy/auth/fragments/react/sign-up-fields.md
  docs/ui-legacy/auth/fragments/react/tutorial.md
  docs/ui-legacy/auth/fragments/vue/authenticator.md
  docs/ui-legacy/auth/fragments/vue/connect.md
  docs/ui-legacy/auth/menu.json
  docs/ui-legacy/auth/overview.md
  docs/ui-legacy/fragments/angular/overview.md
  docs/ui-legacy/fragments/confirm-sign-in-attributes.md
  docs/ui-legacy/fragments/confirm-sign-up-attributes.md
  docs/ui-legacy/fragments/forgot-password-attributes.md
  docs/ui-legacy/fragments/interactions-attributes.md
  docs/ui-legacy/fragments/photo-picker-attributes.md
  docs/ui-legacy/fragments/react/overview.md
  docs/ui-legacy/fragments/set-mfa-attributes.md
  docs/ui-legacy/fragments/sign-in-attributes.md
  docs/ui-legacy/fragments/sign-out-attributes.md
  docs/ui-legacy/fragments/sign-up-attributes.md
  docs/ui-legacy/fragments/sign-up-fields.md
  docs/ui-legacy/fragments/vue/overview.md
  docs/ui-legacy/interactions/chatbot.md
  docs/ui-legacy/interactions/fragments/angular/chatbot.md
  docs/ui-legacy/interactions/fragments/react/chatbot.md
  docs/ui-legacy/interactions/fragments/vue/chatbot.md
  docs/ui-legacy/interactions/menu.json
  docs/ui-legacy/interactions/overview.md
  docs/ui-legacy/menu.json
  docs/ui-legacy/storage/customization.md
  docs/ui-legacy/storage/fragments/angular/photo-picker.md
  docs/ui-legacy/storage/fragments/angular/s3-album.md
  docs/ui-legacy/storage/fragments/react/customization.md
  docs/ui-legacy/storage/fragments/react/photo-picker.md
  docs/ui-legacy/storage/fragments/react/s3-album.md
  docs/ui-legacy/storage/fragments/react/s3-image.md
  docs/ui-legacy/storage/fragments/react/tracking-events.md
  docs/ui-legacy/storage/fragments/vue/photo-picker.md
  docs/ui-legacy/storage/fragments/vue/s3-album.md
  docs/ui-legacy/storage/fragments/vue/s3-image.md
  docs/ui-legacy/storage/menu.json
  docs/ui-legacy/storage/overview.md
  docs/ui-legacy/storage/photo-picker.md
  docs/ui-legacy/storage/s3-album.md
  docs/ui-legacy/storage/s3-image.md
  docs/ui-legacy/storage/tracking-events.md
  docs/ui-legacy/ui-legacy.md
  docs/ui-legacy/xr/fragments/angular/sumerian-scene.md
  docs/ui-legacy/xr/fragments/react/sumerian-scene.md
  docs/ui-legacy/xr/fragments/vue/sumerian-scene.md
  docs/ui-legacy/xr/menu.json
  docs/ui-legacy/xr/overview.md
  docs/ui-legacy/xr/sumerian-scene.md
Labels: v2

#1284 [v2-preview] Update iOS push-notifications.md to use .p8 and Amplify CLI flow
  docs/sdk/push-notifications/fragments/ios/getting-started.md
Labels: iOS, v2

#1465 Default and impossible paths
  capi/src/inject/filtered-version-routes.ts
  client/src/docs-ui/choose-anchor/choose-anchor.tsx
  client/src/docs-ui/internal-link/internal-link.tsx
Labels: v2

#1467 chore: re-enable link errors and support query strings in md
  capi/src/visitors/links.ts
  docs/lib/push-notifications/fragments/js/getting-started.md
Labels: v2

#1475 Update CLI installation steps to match getting started
  docs/cli/start/install.md
Labels: v2

#1468 a few small fixes: code formatting, mispelling
  docs/lib/auth/fragments/js/emailpassword.md
  docs/lib/graphqlapi/fragments/js/getting-started.md
Labels: v2

#1003 Made all of the links to resources clickable
  android/push-notifications-setup-fcm.md
Labels: Android

#1464 Updated descriptions of Admin Queries API routes.
  docs/cli/auth/admin.md
Labels: v2

#1483 updates to JS predictions and analytics categories
  docs/lib/analytics/fragments/js/getting-started.md
  docs/lib/analytics/fragments/js/record.md
  docs/lib/analytics/fragments/js/storing.md
  docs/lib/analytics/fragments/js/streaming.md
  docs/lib/predictions/fragments/js/getting-started.md
  docs/lib/predictions/fragments/js/identify-entity.md
  docs/lib/predictions/fragments/js/identify-text.md
  docs/lib/predictions/fragments/js/interpret.md
  docs/lib/predictions/fragments/js/intro.md
  docs/lib/predictions/fragments/js/label-image.md
  docs/lib/predictions/fragments/js/text-speech.md
  docs/lib/predictions/fragments/js/transcribe.md
  docs/lib/predictions/fragments/js/translate.md
Labels: v2

#1494 updates / fixes to React GraphQL API Getting Started, also fixes #1378
  docs/start/getting-started/fragments/react/api.md
Labels: v2

#1480 V2 preview select mfa
  docs/ui/auth/fragments/angular/select-mfa-type.md
  docs/ui/auth/fragments/ionic/select-mfa-type.md
  docs/ui/auth/fragments/react/select-mfa-type.md
  docs/ui/auth/fragments/vue/select-mfa-type.md
  docs/ui/auth/menu.json
  docs/ui/auth/select-mfa-type.md
Labels: v2

#1537 Append n to numbered h2 and h3 IDs to prevent query selection failure
  capi/src/init-node/html-to-hyperscript.ts
  docs/ui/auth/fragments/react/authenticator.md
Labels: v2

#1548 by ID example of JS DataStore Observe, re issue #1545
  docs/lib/datastore/fragments/js/data-access/observe-snippet.md
Labels: v2

#1396 add @http directive documentation to directives.md
  docs/cli/graphql-transformer/directives.md
Labels: v2

#1452 iOS - Bump all to 2.13.0
  ios/predictions.md
  sdk/ios/analytics.md
  sdk/ios/api.md
  sdk/ios/authentication.md
  sdk/ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md
  sdk/ios/pubsub.md
  sdk/ios/push-notifications.md
  sdk/ios/storage.md
Labels: v2

#1565 Add Sign in with Apple federated identity docs for iOS
  docs/sdk/auth/fragments/ios/federated-identities.md
Labels: iOS

#1567 Add Sign in with Apple federated identity docs for Android
  docs/sdk/auth/fragments/android/federated-identities.md
Labels: Android

#1574 Add, remove and rework push notifications section
  docs/lib/push-notifications/fragments/js/getting-started.md
  docs/lib/push-notifications/fragments/js/overview.md
  docs/lib/push-notifications/fragments/js/working-with-api.md
  docs/lib/push-notifications/getting-started.md
  docs/lib/push-notifications/overview.md
  docs/lib/push-notifications/testing.md
  docs/lib/push-notifications/working-with-api.md
Labels: v2

#1577 remove js specific content from ios
  docs/lib/restapi/fetch.md
  docs/lib/restapi/fragments/android/authz.md
  docs/lib/restapi/fragments/ios/authz.md
  docs/lib/restapi/fragments/ios/fetch.md
  docs/lib/restapi/fragments/ios/getting-started.md
  docs/lib/restapi/fragments/ios/update.md
  docs/lib/restapi/update.md
Labels: v2

#1579 review iOS SDK PubSub and fix broken links
  docs/sdk/pubsub/fragments/android/getting-started.md
  docs/sdk/pubsub/fragments/android/working-api.md
  docs/sdk/pubsub/fragments/ios/getting-started.md
  docs/sdk/pubsub/fragments/ios/working-api.md
Labels: v2

#1580 review and fix Amplify iOS Storage
  docs/lib/storage/fragments/ios/configureaccess.md
  docs/lib/storage/fragments/ios/download.md
  docs/lib/storage/fragments/ios/escapehatch.md
  docs/lib/storage/fragments/ios/getting-started.md
  docs/lib/storage/fragments/ios/list.md
  docs/lib/storage/fragments/ios/remove.md
  docs/lib/storage/fragments/ios/upload.md
Labels: v2

#1575 React Native Improvements
  client/src/docs-ui/menu/menu.tsx
  docs/ui-legacy/customization/fragments/react-native/theming.md
  docs/ui-legacy/customization/menu.json
  docs/ui-legacy/customization/theming.md
  docs/ui-legacy/menu.json
  docs/ui-legacy/ui-legacy.md
  docs/ui/api/connect.md
  docs/ui/api/fragments/react-native/connect.md
  docs/ui/api/menu.json
  docs/ui/auth/fragments/react-native/authenticator.md
  docs/ui/interactions/chatbot.md
  docs/ui/interactions/fragments/react-native/chatbot.md
  docs/ui/interactions/menu.json
  docs/ui/menu.json
  docs/ui/storage/customization.md
  docs/ui/storage/fragments/react-native/customization.md
  docs/ui/storage/fragments/react-native/photo-picker.md
  docs/ui/storage/fragments/react-native/s3-album.md
  docs/ui/storage/fragments/react-native/s3-image.md
  docs/ui/storage/fragments/react-native/tracking-events.md
  docs/ui/storage/menu.json
  docs/ui/storage/photo-picker.md
  docs/ui/storage/s3-album.md
  docs/ui/storage/s3-image.md
  docs/ui/storage/tracking-events.md
Labels: v2

#1588 push notification content and links review
  docs/sdk/push-notifications/fragments/android/messaging-campaign.md
  docs/sdk/push-notifications/fragments/ios/getting-started.md
  docs/sdk/push-notifications/fragments/ios/messaging-campaign.md
Labels: v2
