Repository aws-amplify/docs, pull requests merged in 2020-03, with the labels that each got.

#1149 Adds note about GUEST user state on first initialize
  sdk/android/authentication.md
Labels: Android

#1114 [IoT] Document instructions for use of custom authorizers in IoT
  android/pubsub.md
Labels: Android

#1263 Making the video / read options for `install amplify CLI` section clearer
  docs/start/getting-started/installation.md
Labels: v2

#1264 Made command defaults highlighted
  docs/start/getting-started/fragments/android/setup.md
  docs/start/getting-started/fragments/angular/data-model.md
  docs/start/getting-started/fragments/ionic/data-model.md
  docs/start/getting-started/fragments/ios/setup.md
  docs/start/getting-started/fragments/react/api.md
  docs/start/getting-started/fragments/reactnative/api.md
  docs/start/getting-started/fragments/vanillajs/data-model.md
  docs/start/getting-started/fragments/vue/data-model.md
Labels: v2

#1238 style: remove webkit styles
  client/src/docs-ui/menu-group/menu-group.style.ts
Labels: v2

#1244 style: fix next prev button spacings on mobile
  client/src/docs-ui/next-previous/next-previous.style.ts
Labels: v2

#1262 Small update to setup step in React Native getting started guide
  docs/start/getting-started/fragments/reactnative/setup.md
Labels: v2

#1267 Rework cli nav
  docs/cli/auth/menu.json
  docs/cli/categories/hosting.md
  docs/cli/categories/menu.json
  docs/cli/cli.md
  docs/cli/function/function.md
  docs/cli/function/menu.json
  docs/cli/graphql-transformer/menu.json
  docs/cli/graphql-transformer/overview.md
  docs/cli/hosting/hosting.md
  docs/cli/hosting/menu.json
  docs/cli/menu.json
  docs/cli/restapi/menu.json
  docs/cli/restapi/restapi.md
  docs/cli/start/install.md
  docs/cli/start/menu.json
  docs/cli/start/start.md
  docs/cli/storage/menu.json
  docs/cli/storage/storage.md
  docs/cli/usage/customcf.md
  docs/cli/usage/iam.md
  docs/cli/usage/menu.json
  docs/cli/usage/mock.md
Labels: v2

#1261 Update sdk/lib landing pages, add call to action button
  docs/fragments/lib/android-sdk.md
  docs/fragments/lib/android.md
  docs/fragments/lib/ios-sdk.md
  docs/fragments/lib/ios.md
  docs/fragments/lib/js.md
  docs/lib/lib.md
  docs/lib/xr/fragments/sceneapi.md
  docs/lib/xr/fragments/start.md
  docs/sdk/sdk.md
Labels: v2

#1255 Dismissable Feedback Callout
  client/src/components.d.ts
  client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap
  client/src/docs-ui/feedback-callout/feedback-callout.spec.ts
  client/src/docs-ui/feedback-callout/feedback-callout.style.ts
  client/src/docs-ui/feedback-callout/feedback-callout.tsx
  client/src/docs-ui/menu/__snapshots__/menu.spec.ts.snap
  client/src/docs-ui/menu/menu.tsx
Labels: v2

#1256 style: adjust paragraph margin styles within callout components
  client/src/amplify-ui/callout/__snapshots__/callout.spec.ts.snap
  client/src/amplify-ui/callout/callout.style.ts
Labels: v2

#1266 chore: update stencil version, fix breaks, enable prerendering
  .eslintrc
  capi/package.json
  capi/src/write/get-page.ts
  capi/src/write/stencil-renderer.ts
  client/src/amplify-ui/responsive-grid/responsive-grid.tsx
  client/src/amplify-ui/sidebar-layout/sidebar-layout-sidebar/sidebar-layout-sidebar.tsx
  client/src/amplify-ui/toc/toc-content/toc-content.tsx
  client/src/amplify-ui/toc/toc-provider/toc-provider.tsx
  client/src/amplify-ui/toc/toc/toc.tsx
  client/src/components.d.ts
  client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap
  client/src/docs-ui/feedback-callout/feedback-callout.tsx
  client/src/docs-ui/in-page-link/in-page-link.tsx
  client/src/docs-ui/internal-link/internal-link.tsx
  client/src/docs-ui/menu-group/menu-group.tsx
  client/src/docs-ui/page/page.tsx
  client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap
  client/src/docs-ui/repo-actions/repo-actions.tsx
  client/src/docs-ui/select-anchor/select-anchor.tsx
  client/src/index.html
  client/src/utils/hyperscript/index.ts
  client/src/utils/track.ts
  client/stencil.config.ts
  package.json
  tasks/build.ts
  tsconfig.base.json
  yarn.lock
Labels: v2

#1272 Update to SDK/Lib landing pages and switching logic
  client/src/docs-ui/menu/menu.tsx
  docs/fragments/lib/android-sdk.md
  docs/fragments/lib/android.md
  docs/fragments/lib/ios-sdk.md
  docs/fragments/lib/ios.md
  docs/lib/lib.md
  docs/sdk/sdk.md
Labels: v2

#1270 Update hosting doc with landing page changes
  client/src/docs-ui/universal-nav/universal-nav.tsx
  client/src/index.html
  client/src/manifest.json
  docs/cli/hosting/hosting.md
  docs/docs.md
Labels: v2

#1277 Update Amplify iOS/Android landing page
  docs/fragments/lib/android.md
  docs/fragments/lib/ios.md
Labels: v2

#1278 New feedback button text and CLI description
  client/src/docs-ui/feedback-callout/feedback-callout.tsx
  client/src/docs-ui/repo-actions/repo-actions.tsx
  docs/cli/cli.md
Labels: v2

#1285 Fix snapshots
  client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap
  client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap
  client/src/docs-ui/universal-nav/__snapshots__/universal-nav.spec.ts.snap
Labels: v2

#1280 fix: sanitize unhighlighted code blocks for placement in html before …
  capi/package.json
  capi/src/init-node/index.ts
  docs/lib/datastore/fragments/android/data-access.md
  yarn.lock
Labels: v2

#1289 [v2-preview] CircleCI dummy config
  .circleci/config.yml
Labels: v2

#1292 Remove reference to DataStore from SDK next steps
  docs/start/getting-started/fragments/android/nextsteps.md
  docs/start/getting-started/fragments/ios/nextsteps.md
Labels: v2

#1282 fix: reflect v2-preview branch in repo-actions edit
  client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap
  client/src/docs-ui/repo-actions/repo-actions.tsx
Labels: v2

#1297 style: prevent hiding of fac when menu expanded, update x graphic
  client/src/amplify-ui/sidebar-layout/sidebar-layout-toggle/sidebar-layout-toggle.style.ts
  client/src/amplify-ui/sidebar-layout/sidebar-layout-toggle/sidebar-layout-toggle.tsx
  client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap
  client/src/docs-ui/feedback-callout/feedback-callout.style.ts
  client/src/docs-ui/feedback-callout/feedback-callout.tsx
  client/src/docs-ui/page/__snapshots__/page.spec.ts.snap
  client/src/docs-ui/page/page.style.ts
  client/src/docs-ui/page/page.tsx
  docs/assets/close.svg
Labels: v2

#1298 chore: set sdk to lib root when in android or ios
  client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap
  client/src/docs-ui/secondary-nav/secondary-nav.tsx
Labels: v2

#1299 Fix links
  docs/fragments/lib/js.md
  docs/lib/auth/fragments/js/migrate.md
Labels: v2

#1308 Fix incorrect titles for the storage "Download/Upload files" docs
  docs/lib/storage/download.md
  docs/lib/storage/upload.md
Labels: v2

#1319 fix: how links are parsed and transformed in capi
  capi/src/visitors/image-references.ts
  capi/src/visitors/links.ts
  client/src/amplify-ui/styles/variables.ts
  client/src/docs-ui/chat-button/__snapshots__/chat-button.spec.ts.snap
  client/src/docs-ui/chat-button/chat-button.style.ts
  client/src/docs-ui/chat-button/chat-button.tsx
  client/src/docs-ui/internal-link/internal-link.tsx
  docs/lib/analytics/fragments/ios/start.md
  docs/start/start.md
Labels: v2

#1316 UI Component documentation
  capi/src/init-node/html-to-hyperscript.ts
  client/src/amplify-ui/styles/elements.ts
  client/src/amplify-ui/styles/media.ts
  client/src/components.d.ts
  client/src/docs-ui/internal-link/internal-link.tsx
  client/src/docs-ui/menu/menu.style.ts
  client/src/docs-ui/menu/menu.tsx
  client/src/docs-ui/page/page.tsx
  client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap
  client/src/docs-ui/secondary-nav/secondary-nav.style.ts
  client/src/docs-ui/secondary-nav/secondary-nav.tsx
  client/src/docs-ui/ui-component-props/__snapshots__/ui-component-props.spec.ts.snap
  client/src/docs-ui/ui-component-props/ui-component-props.spec.ts
  client/src/docs-ui/ui-component-props/ui-component-props.style.ts
  client/src/docs-ui/ui-component-props/ui-component-props.tsx
  client/src/docs-ui/version-switch/version-switch.style.ts
  client/src/docs-ui/version-switch/version-switch.tsx
  client/src/docs-ui/version-switch/version-switch.types.ts
  client/src/index.ts
  docs/ui-legacy/auth/installation.md
  docs/ui-legacy/auth/menu.json
  docs/ui-legacy/menu.json
  docs/ui-legacy/ui-legacy.md
  docs/ui/auth/authenticator.md
  docs/ui/auth/confirm-sign-in.md
  docs/ui/auth/confirm-sign-up.md
  docs/ui/auth/forgot-password.md
  docs/ui/auth/fragments/angular/usage.md
  docs/ui/auth/fragments/react/usage.md
  docs/ui/auth/fragments/vue/usage.md
  docs/ui/auth/greetings.md
  docs/ui/auth/menu.json
  docs/ui/auth/require-new-password.md
  docs/ui/auth/sign-in.md
  docs/ui/auth/sign-out.md
  docs/ui/auth/sign-up.md
  docs/ui/auth/totp-setup.md
  docs/ui/auth/verify-contact.md
  docs/ui/customization/menu.json
  docs/ui/customization/slots.md
  docs/ui/customization/theming.md
  docs/ui/fragments/angular/installation.md
  docs/ui/fragments/react-native/not-supported.md
  docs/ui/fragments/react/installation.md
  docs/ui/fragments/vue/installation.md
  docs/ui/menu.json
  docs/ui/ui.md
  package.json
  yarn.lock
Labels: v2

#1325 Restructuring auth category in JS lib
  docs/lib/auth/advanced.md
  docs/lib/auth/challenge.md
  docs/lib/auth/emailpassword.md
  docs/lib/auth/events.md
  docs/lib/auth/fragments/js/advanced.md
  docs/lib/auth/fragments/js/events.md
  docs/lib/auth/fragments/js/getting-started.md
  docs/lib/auth/fragments/js/migrate.md
  docs/lib/auth/fragments/js/start.md
  docs/lib/auth/fragments/js/switch-auth.md
  docs/lib/auth/getting-started.md
  docs/lib/auth/manageusers.md
  docs/lib/auth/menu.json
  docs/lib/auth/migrate.md
  docs/lib/auth/overview.md
  docs/lib/auth/start.md
  docs/lib/auth/switch-auth.md
Labels: v2

#1323 Fix link to the CLI docs
  docs/sdk/storage/fragments/android/getting-started.md
Labels: v2

#1322 Update versions to latest release
  docs/lib/analytics/fragments/android/start.md
  docs/lib/storage/fragments/android/start.md
Labels: v2

#1320 Add note about accessing legacy external storage
  docs/sdk/storage/fragments/android/getting-started.md
Labels: v2

#1321 Add note about GUEST user state on initialize
  docs/sdk/auth/fragments/android/guest-access.md
Labels: v2

#1328 Swap upload and download pages for Android Storage
  docs/lib/storage/fragments/android/download.md
  docs/lib/storage/fragments/android/upload.md
Labels: v2

#1290 [v2-preview] Remove backend build from Amplify console config
  amplify.yml
Labels: v2

#1334 Added new label
  client/src/docs-ui/universal-nav/__snapshots__/universal-nav.spec.ts.snap
  client/src/docs-ui/universal-nav/universal-nav.style.ts
  client/src/docs-ui/universal-nav/universal-nav.tsx
Labels: v2

#1344 fix: mobile link override regression
  capi/src/visitors/links.ts
Labels: v2

#1336 fix: fixed toc style and behavior issues
  client/src/amplify-ui/toc/toc/__snapshots__/toc.spec.ts.snap
  client/src/amplify-ui/toc/toc/toc.style.ts
  client/src/amplify-ui/toc/toc/toc.tsx
  client/src/docs-ui/in-page-link/in-page-link.tsx
  client/src/docs-ui/page/__snapshots__/page.spec.ts.snap
  client/src/docs-ui/page/page.style.ts
  client/src/docs-ui/ui-component-props/__snapshots__/ui-component-props.spec.ts.snap
  client/src/docs-ui/ui-component-props/ui-component-props.tsx
  client/src/utils/get-element-top.ts
Labels: v2

#1326 [Android docs] Updating android code snippets to reflect upcoming API…
  docs/lib/analytics/fragments/android/identifyuser.md
  docs/lib/analytics/fragments/android/record.md
  docs/lib/analytics/fragments/android/start.md
  docs/lib/datastore/fragments/android/relational.md
  docs/lib/getting-started/fragments/android/integrate.md
  docs/lib/graphqlapi/fragments/android/mutate-data.md
  docs/lib/graphqlapi/fragments/android/query-data.md
  docs/lib/graphqlapi/fragments/android/start.md
  docs/lib/graphqlapi/fragments/android/subscribe-data.md
  docs/lib/restapi/fragments/android/start.md
  docs/lib/storage/fragments/android/download.md
  docs/lib/storage/fragments/android/list.md
  docs/lib/storage/fragments/android/remove.md
  docs/lib/storage/fragments/android/start.md
  docs/lib/storage/fragments/android/upload.md
  docs/sdk/auth/fragments/android/how-it-works.md
Labels: v2

#1354 Add fixed width for left table headers
  client/src/docs-ui/ui-component-props/ui-component-props.style.ts
Labels: v2

#1364 fix: nav back bug
  capi/src/visitors/links.ts
  capi/src/write/stencil-renderer.ts
  client/src/amplify-ui/toc/toc/__snapshots__/toc.spec.ts.snap
  client/src/amplify-ui/toc/toc/toc.style.ts
  client/src/components.d.ts
  client/src/docs-ui/page/__snapshots__/page.spec.ts.snap
  client/src/docs-ui/page/page.spec.ts
  client/src/docs-ui/page/page.tsx
  client/src/router.tsx
  client/src/utils/hyperscript/index.ts
  client/src/utils/pop-state.ts
Labels: v2

#1383 Use shadow and transition for card UI
  client/src/amplify-ui/card/__snapshots__/card.spec.ts.snap
  client/src/amplify-ui/card/card.style.ts
  client/src/docs-ui/choose-anchor/choose-anchor.tsx
  client/src/docs-ui/choose-integration-anchor/__snapshots__/choose-integration-anchor.spec.ts.snap
  client/src/docs-ui/choose-integration-anchor/choose-integration-anchor.tsx
  client/src/docs-ui/footer/__snapshots__/footer.spec.ts.snap
  client/src/docs-ui/footer/footer.style.ts
  docs/docs.md
  docs/fragments/features-grid.md
Labels: v2

#1384 fix: in-page-links being transformed improperly
  capi/src/visitors/links.ts
Labels: v2

#1385 Fixed broken links on Landing Page
  docs/fragments/features-grid.md
Labels: v2

#1382 chore:(storage-docs) Update broken links and missing content
  docs/lib/storage/fragments/js/autotrack.md
  docs/lib/storage/fragments/js/configureaccess.md
  docs/lib/storage/fragments/js/download.md
  docs/lib/storage/fragments/js/getting-started.md
  docs/lib/storage/fragments/js/list.md
  docs/lib/storage/fragments/js/remove.md
  docs/lib/storage/fragments/js/upload.md
  docs/lib/storage/triggers.md
Labels: JavaScript, v2

#1365 Clarify Android wording and ref latest versions
  docs/lib/getting-started/fragments/android/setup.md
Labels: v2
