Repository aws-amplify/docs, pull requests merged in 2020-10, with the labels that each got.

#2114 Update pinpoint SDK notifications handling for iOS 10 and above
  docs/sdk/push-notifications/fragments/ios/getting-started.md
Labels: iOS

#2510 iOS tutorial replace "then" with "them"
  docs/start/getting-started/fragments/ios/generate-model.md
Labels: iOS

#2552 fix:(react-native-getting-started) fix typo
  docs/start/getting-started/fragments/reactnative/api.md
Labels: Ready for Review

#1819 Add Warning message for manually update CloudFromation resources
  docs/cli/cli.md
Labels: CLI

#2558 chore: Add CODEOWNERS file
  .github/CODEOWNERS
  docs/cli/restapi/testing.md
Labels: Ready for Review

#2581 fix(reactnative): correct directory path
  docs/start/getting-started/fragments/reactnative/setup.md
Labels: Ready for Review

#2332 Add documentation for multiple redirect URIs
  docs/lib/auth/fragments/js/social.md
Labels: Ready for Review

#2530 docs: remove unused CSS property in api.md
  docs/start/getting-started/fragments/react/api.md
Labels: Ready for Review

#2524 Fix code block header not updating when switching platforms
  client/src/amplify-ui/block-switcher/block-switcher.spec.ts
  client/src/amplify-ui/block-switcher/block-switcher.tsx
  client/src/components.d.ts
  client/src/docs-ui/page/page.tsx
  client/src/docs-ui/page/page.types.ts
Labels: Ready for Review

#1797 Fix typo with js graphql documentation
  docs/lib/graphqlapi/fragments/js/mutate-data.md
Labels: JavaScript

#2486 Fix/vue auth state mgmt
  docs/ui/auth/fragments/vue/auth-state-management.md
Labels: Ready for Review

#2522 feat:added warning for searchable
  docs/cli/graphql-transformer/directives.md
Labels: Ready for Review

#2315 Add iOS developer menu documentation
  docs/images/debugging/iosDevMenu.png
  docs/lib/debugging/dev-menu.md
  docs/lib/debugging/fragments/ios/dev-menu/setup.md
  docs/lib/debugging/fragments/ios/dev-menu/usage.md
  docs/lib/debugging/fragments/native_common/dev-menu/common.md
Labels: Pending Release, iOS

#2490 Update setup.md
  docs/start/getting-started/fragments/angular/setup.md
Labels: Ready for Review

#2557 Breaks out directive sections
  client/src/components.d.ts
  docs/cli/auth/groups.md
  docs/cli/function/function.md
  docs/cli/graphql-transformer/auth.md
  docs/cli/graphql-transformer/codegen.md
  docs/cli/graphql-transformer/connection.md
  docs/cli/graphql-transformer/directives.md
  docs/cli/graphql-transformer/function.md
  docs/cli/graphql-transformer/http.md
  docs/cli/graphql-transformer/key.md
  docs/cli/graphql-transformer/menu.json
  docs/cli/graphql-transformer/model.md
  docs/cli/graphql-transformer/predictions.md
  docs/cli/graphql-transformer/resolvers.md
  docs/cli/graphql-transformer/searchable.md
  docs/cli/graphql-transformer/versioned.md
  docs/cli/plugins/authoring.md
  docs/cli/plugins/fragments/custom-transformer.md
  docs/cli/usage/lambda-triggers.md
  docs/cli/usage/mock.md
  docs/guides/api-graphql/building-a-form-api.md
  docs/guides/api-graphql/lambda-resolvers.md
  docs/guides/api-graphql/query-with-sorting.md
  docs/lib/datastore/auth-model.md
  docs/lib/datastore/fragments/native_common/relational.md
  docs/lib/graphqlapi/fragments/android/getting-started.md
  docs/lib/graphqlapi/fragments/js/getting-started.md
  docs/start/getting-started/fragments/angular/data-model.md
  docs/start/getting-started/fragments/ionic/data-model.md
  docs/start/getting-started/fragments/next/api.md
  docs/start/getting-started/fragments/react/api.md
  docs/start/getting-started/fragments/reactnative/api.md
  docs/start/getting-started/fragments/vanillajs/data-model.md
  docs/start/getting-started/fragments/vue/data-model.md
Labels: Ready for Review

#2610 feat: auto-generate documentations for css and slots (#2533)
  client/src/components.d.ts
  client/src/constants/strings.ts
  client/src/docs-ui/component-playground/component-playground.styles.scss
  client/src/docs-ui/component-playground/component-playground.tsx
  client/src/docs-ui/ui-component-props/__snapshots__/ui-component-props.spec.ts.snap
  client/src/docs-ui/ui-component-props/table-generator.tsx
  client/src/docs-ui/ui-component-props/ui-component-props.tsx
  client/src/docs-ui/ui-component-props/ui-component-props.types.tsx
  docs/ui/auth/fragments/angular/select-mfa-type.md
  docs/ui/auth/fragments/angular/sign-out.md
  docs/ui/auth/fragments/ionic/select-mfa-type.md
  docs/ui/auth/fragments/ionic/sign-out.md
  docs/ui/auth/fragments/react/sign-out.md
  docs/ui/auth/fragments/vue/sign-out.md
  docs/ui/auth/fragments/web/authenticator.md
  docs/ui/interactions/fragments/web/chatbot/customization.md
  docs/ui/interactions/fragments/web/chatbot/properties-attributes.md
  docs/ui/interactions/fragments/web/chatbot/properties-jsx.md
  docs/ui/interactions/fragments/web/chatbot/usage.md
  docs/ui/storage/fragments/web/s3-album.md
  docs/ui/storage/fragments/web/s3-image-picker.md
  docs/ui/storage/fragments/web/s3-image.md
  docs/ui/storage/fragments/web/s3-text-picker.md
  docs/ui/storage/fragments/web/s3-text.md
  yarn.lock
Labels: Dependency Update
