Repository aws-amplify/docs, pull requests merged in 2021-03, with the labels that each got.

#2999 External links were tracking but not being associated with the docs project; this fixes that
  client/src/utils/track.ts
Labels: Docs Site (Itself)

#2990 fix: add error event in API subscription sample code
  docs/lib/graphqlapi/fragments/js/subscribe-data.md
Labels: JavaScript

#3002 FIx switching framework kicking users back to the start of their browsing
  client/src/docs-ui/select-anchor/select-anchor.tsx
Labels: Docs Site (Itself)

#2992 feat: add callout to DataStore.observe
  docs/lib/datastore/fragments/js/real-time/observe-snippet.md
Labels: JavaScript

#3037 Update customui.md to fix broken React Native theme link
  docs/lib/auth/fragments/js/customui.md
Labels: JavaScript

#2891 add pipenv info for installing boto3
  docs/guides/functions/dynamodb-from-python-lambda.md
Labels: Guides

#3066 fix(getting-started): clarify Vue 2 vs Vue 3 installation guide
  docs/start/getting-started/fragments/vue/setup.md
Labels: JavaScript

#3054 Purge @ts-ignore statements by declaring types on globals
  client/src/amplify-ui/responsive-grid/responsive-grid.tsx
  client/src/amplify-ui/toc/toc-provider/toc-provider.tsx
  client/src/amplify-ui/toc/toc/toc.tsx
  client/src/docs-ui/in-page-link/in-page-link.tsx
  client/src/docs-ui/search-bar/search-bar.tsx
  client/src/docs-ui/select-anchor/select-anchor.tsx
  client/src/globals.d.ts
  client/src/utils/track.ts
Labels: Docs Site (Itself)
