Repository aws-amplify/docs, pull requests merged in 2021-09, with the labels that each got.

#3510 Bump package versions
  package.json
  yarn.lock
Labels: Docs Site (Itself)

#3512 Correct "edit this page on github" links on product roots and issue creation content
  .github/workflows/build.yml
  next.config.js
  src/components/Menu/Directory/index.tsx
  src/components/Menu/FilterSelect/index.tsx
  src/components/Menu/RepoActions/index.tsx
  src/components/Menu/VersionSwitcher/index.tsx
  src/components/Menu/index.tsx
  src/components/NextPrevious/index.tsx
  src/components/Page/index.tsx
  src/pages/ChooseFilterPage.tsx
  tsconfig.json
Labels: Docs Site (Itself)

#3500 Update PubSub policy creation docs
  docs/lib/pubsub/fragments/js/getting-started.md
  docs/sdk/pubsub/fragments/android/getting-started.md
  docs/sdk/pubsub/fragments/ios/getting-started.md
  src/fragments/sdk/pubsub/android/getting-started.mdx
  src/fragments/sdk/pubsub/ios/getting-started.mdx
Labels: Ready for Review

#3566 Fully remove docsearch CDN
  src/components/Layout/index.tsx
Labels: Docs Site (Itself)

#3571 feat: add PubSub provider removal doc
  docs/lib/pubsub/fragments/js/getting-started.md
  src/fragments/lib/pubsub/js/getting-started.mdx
Labels: Ready for Review

#3574 Remove whitespace to fix codeblock in android auth getting-started
  src/fragments/lib/auth/android/getting_started/30_initAuth.mdx
Labels: Android

#3409 Amplify Mock: Add note about JDK issues on Apple Silicon
  docs/cli/usage/mock.md
Labels: first-time-contributor

#3560 Show table of contents on /ui/interactions/chatbot/q/framework/react...
  .github/workflows/build.yml
  src/components/TableOfContents/index.tsx
  src/components/TableOfContents/styles.tsx
  src/components/UiComponentProps/index.tsx
  src/plugins/headings.tsx
  src/utils/get-element-top.ts
  src/utils/traverseHeadings.ts
Labels: Docs Site (Itself)

#3573 SEO improvements
  .gitignore
  generatePathMap.cjs.js
  next.config.js
  package.json
  public/robots.txt
  src/components/ExternalLink/index.tsx
  src/components/FeaturesGrid/index.tsx
  src/components/Footer/index.tsx
  src/components/LandingHeroCTA/index.tsx
  src/components/Layout/index.tsx
  src/components/LinkBanner/index.tsx
  src/components/Menu/FilterSelect/index.tsx
  src/components/Page/index.tsx
  src/components/UniversalNav/index.tsx
  src/constants/img.ts
  src/fragments/features-grid.mdx
  src/pages/ChooseFilterPage.tsx
  src/pages/console/adminui/start.mdx
  src/pages/console/data/data-model.mdx
  src/pages/console/index.mdx
  src/pages/docs.mdx
  src/pages/index.tsx
  src/pages/lib/analytics/getting-started.tsx
  src/pages/lib/auth/getting-started.tsx
  src/pages/lib/datastore/getting-started.tsx
  src/pages/lib/graphqlapi/getting-started.tsx
  src/pages/lib/interactions/getting-started.tsx
  src/pages/lib/predictions/getting-started.tsx
  src/pages/lib/pubsub/getting-started.tsx
  src/pages/lib/push-notifications/getting-started.tsx
  src/pages/lib/restapi/getting-started.tsx
  src/pages/lib/storage/getting-started.tsx
  src/pages/lib/xr/getting-started.tsx
  src/plugins/internal-link.tsx
  tasks/generate-sitemap.ts
Labels: Docs Site (Itself)

#3615 chore(Android): bump Amplify Android version
  docs/lib/analytics/fragments/android/getting-started/20_installLib.md
  docs/lib/auth/fragments/android/getting_started/20_installLib.md
  docs/lib/datastore/fragments/android/getting-started/20_installLib.md
  docs/lib/datastore/fragments/android/sync/10-installPlugin.md
  docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
  docs/lib/graphqlapi/fragments/android/getting-started.md
  docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
  docs/lib/predictions/fragments/android/getting-started/30_installLib.md
  docs/lib/project-setup/fragments/android/coroutines/coroutines.md
  docs/lib/project-setup/fragments/android/create-application/20_gradle.md
  docs/lib/project-setup/fragments/android/rxjava/rxjava.md
  docs/lib/restapi/fragments/android/getting-started/20_installLib.md
  docs/lib/storage/fragments/android/getting-started/20_installLib.md
  docs/start/getting-started/fragments/android/setup.md
  src/fragments/lib/analytics/android/getting-started/20_installLib.mdx
  src/fragments/lib/auth/android/getting_started/20_installLib.mdx
  src/fragments/lib/datastore/android/getting-started/20_installLib.mdx
  src/fragments/lib/datastore/android/sync/10-installPlugin.mdx
  src/fragments/lib/graphqlapi/android/authz/21_oidc.mdx
  src/fragments/lib/graphqlapi/android/getting-started.mdx
  src/fragments/lib/graphqlapi/android/getting-started/20_installLib.mdx
  src/fragments/lib/predictions/android/getting-started/30_installLib.mdx
  src/fragments/lib/project-setup/android/coroutines/coroutines.mdx
  src/fragments/lib/project-setup/android/create-application/20_gradle.mdx
  src/fragments/lib/project-setup/android/rxjava/rxjava.mdx
  src/fragments/lib/restapi/android/getting-started/20_installLib.mdx
  src/fragments/lib/storage/android/getting-started/20_installLib.mdx
  src/fragments/start/getting-started/android/setup.mdx
Labels: Android
