Repository aws-amplify/docs, pull requests merged in 2021-04, with the labels that each got.

#3049 Fix reference to AmplifyTotpSetup.
  docs/ui/auth/fragments/web/authenticator.md
Labels: Auth, JavaScript

#3109 fix(flutter/guides): Add missing integration fragments to getting started page
  docs/start/getting-started/installation.md
Labels: Bug, Docs Site (Itself), Ready for Review

#3121 fix: Remove extraneous parenthesis in code sample
  docs/lib/graphqlapi/fragments/js/mutate-data.md
Labels: JavaScript

#3124 Add missing graphqlOperation
  docs/lib/graphqlapi/fragments/js/getting-started.md
Labels: JavaScript

#3146 (fix): `containertag` is correct
  docs/console/console.md
Labels: Docs Site (Itself)

#3148 (update): Auth documentation now refers to current version of UI components
  docs/lib/auth/fragments/js/customui.md
  docs/ui/customization/fragments/react-native/theming.md
Labels: UI

#3147 (fix): Code block duplicating in some scenarios
  client/prerender.config.ts
Labels: Docs Site (Itself)
