Repository aws-amplify/docs, pull requests merged in 2021-05, with the labels that each got.

#3162 Update AmplifySignOut buttonText prop to correct case
  docs/ui/auth/fragments/react/sign-out.md
Labels: React, UI

#3211 Fix results with chunks in GraphQL queries from lambda function
  docs/lib/graphqlapi/fragments/graphql-from-node.md
Labels: CLI

#3253 docs: add brief VTL explainer
  docs/cli/graphql-transformer/resolvers.md
Labels: CLI, Review Overdue

#3252 [Amplify CLI] Changed whom to who for groups.md
  docs/cli/auth/groups.md
Labels: Review Overdue

#3259 Flutter 2.2.0 Instructions
  docs/lib/analytics/fragments/flutter/getting-started/10_preReq.md
  docs/lib/auth/fragments/flutter/getting_started/10_preReq.md
  docs/lib/graphqlapi/fragments/flutter/getting-started/10_preReq.md
  docs/lib/project-setup/fragments/flutter/create-application/10_createProject.md
  docs/lib/restapi/fragments/flutter/getting-started/10_preReq.md
  docs/lib/storage/fragments/flutter/getting-started/10_preReq.md
Labels: Flutter

#3235 chore(repo): update PR template with correct license
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review Overdue

#3228 PM-Update download.md
  docs/lib/storage/fragments/android/download.md
Labels: Review Overdue

#3095 fix(cli/codegen): Migrate `--max-depth` flag to `--maxDepth`
  docs/cli/graphql-transformer/codegen.md
Labels: Review Overdue

#3247 Updated Next.js hosting tutorial to demonstrate support for SSR
  docs/guides/hosting/fragments/nextjs.md
  docs/images/hosting/next/cli-output.png
  docs/images/start-nextjs-deploy-1.png
  docs/images/start-nextjs-deploy-2.png
Labels: Review Overdue

#3065 Add promise rejection for AppSync lambda function
  docs/lib/graphqlapi/fragments/graphql-from-node.md
Labels: CLI

#3128 Add note for using structured types with functions
  docs/cli/graphql-transformer/function.md
Labels: CLI
