Repository aws-amplify/docs, pull requests merged in 2021-06, with the labels that each got.

#2706 fix: provide prop-type on select-mfa-type
  docs/ui/auth/fragments/react/select-mfa-type.md
  docs/ui/auth/fragments/vue/select-mfa-type.md
Labels: JavaScript, Ready for Review, Review Overdue

#3282 docs: added @firehose and @retain directives
  docs/cli/graphql-transformer/directives.md
Labels: CLI, Feature Request

#3210 fix(API): GraphQL/REST API with NONE auth type
  docs/lib/graphqlapi/fragments/native_common/authz/common.md
  docs/lib/restapi/fragments/android/authz/22_none_headers.md
  docs/lib/restapi/fragments/ios/authz/22_none_headers.md
  docs/lib/restapi/fragments/native_common/authz/common.md
Labels: Android, iOS

#3289 fix(iOS): Add SPM guide per category
  docs/lib/analytics/fragments/ios/getting-started/20_installLib.md
  docs/lib/auth/fragments/ios/getting_started/20_installLib.md
  docs/lib/datastore/fragments/ios/getting-started/20_installLib.md
  docs/lib/restapi/fragments/ios/getting-started/20_installLib.md
  docs/lib/storage/fragments/ios/getting-started/20_installLib.md
Labels: iOS

#3290 fix(Storage): iOS storage operations cancel/pause/resume
  docs/lib/storage/fragments/ios/download.md
  docs/lib/storage/fragments/ios/upload.md
Labels: iOS

#3251 Add flutter troubleshooting/upgrades section
  docs/lib/troubleshooting/fragments/flutter/upgrading.md
  docs/lib/troubleshooting/upgrading.md
Labels: Review Overdue

#3288 fix(API): iOS SPM and mutations
  docs/lib/analytics/fragments/ios/getting-started/20_installLib.md
  docs/lib/auth/fragments/ios/getting_started/20_installLib.md
  docs/lib/datastore/fragments/ios/getting-started/20_installLib.md
  docs/lib/graphqlapi/fragments/android/mutate-data.md
  docs/lib/graphqlapi/fragments/flutter/mutate-data.md
  docs/lib/graphqlapi/fragments/ios/getting-started/20_installLib.md
  docs/lib/graphqlapi/fragments/ios/getting-started/30_initapi.md
  docs/lib/graphqlapi/fragments/ios/getting-started/50_createtodo.md
  docs/lib/graphqlapi/fragments/ios/mutate-data.md
  docs/lib/graphqlapi/mutate-data.md
  docs/lib/restapi/fragments/ios/getting-started/20_installLib.md
  docs/lib/storage/fragments/ios/getting-started/20_installLib.md
Labels: iOS

#3350 Fix `ui-component-props` rendering multiple times by removing from prerendering
  client/prerender.config.ts
Labels: Docs Site (Itself)

#3083 fix: use import command instead of editing config files
  docs/lib/auth/fragments/existing-resources.md
  docs/lib/storage/fragments/existing-resources.md
Labels: CLI

#3291 fix(CLI): admin queries API with updated code snippets
  docs/cli/auth/admin.md
Labels: iOS

#3346 Add documentation for handleSignUp
  docs/ui/auth/fragments/angular/overriding-sign-up-submit.md
  docs/ui/auth/fragments/react/overriding-sign-up-submit.md
  docs/ui/auth/fragments/vue/overriding-sign-up-submit.md
  docs/ui/auth/fragments/web/authenticator.md
Labels: Ready for Review
