Repository aws-amplify/docs, pull requests merged in 2021-07, with the labels that each got.

#3392 Remove closing tag with no corresponding opening tag (detected during Next.js migration process)
  docs/ui/auth/fragments/web/authenticator.md
Labels: Docs Site (Itself), UI

#3362 Update Key.md
  docs/cli/graphql-transformer/key.md
Labels: first-time-contributor

#3357 Add link to the React Native Linking guide
  docs/lib/auth/fragments/js/social.md
Labels: first-time-contributor

#3419 Missed the square brackets in the example code
  docs/cli/graphql-transformer/examples.md
Labels: first-time-contributor

#3283 fix(cli/auth): correct multi-auth example outputs
  docs/cli/graphql-transformer/auth.md
Labels: CLI

#3154 change in attach-policy command
  docs/lib/pubsub/fragments/js/getting-started.md
Labels: first-time-contributor
