Repository aws-amplify/docs, pull requests merged in 2022-04, with the labels that each got.

#4174 Change from default to named import.
  src/fragments/start/getting-started/react/setup.mdx
Labels: amplify/js, first-time-contributor

#4175 update default imports to named imports across all files
  src/fragments/lib/analytics/js/getting-started.mdx
  src/fragments/lib/auth/js/getting-started.mdx
  src/fragments/lib/auth/js/mfa.mdx
  src/fragments/lib/geo/js/getting-started.mdx
  src/fragments/lib/in-app-messaging/js/getting-started.mdx
  src/fragments/lib/interactions/js/getting-started.mdx
  src/fragments/lib/predictions/js/getting-started.mdx
  src/fragments/lib/push-notifications/js/getting-started.mdx
  src/fragments/lib/xr/getting-started.mdx
  src/fragments/start/getting-started/angular/data-model.mdx
  src/fragments/start/getting-started/ionic/data-model.mdx
  src/fragments/start/getting-started/react/setup.mdx
  src/fragments/start/getting-started/reactnative/integrate.mdx
  src/fragments/start/getting-started/reactnative/setup.mdx
  src/fragments/start/getting-started/vue/setup.mdx
  src/fragments/ui-legacy/angular/overview.mdx
  src/fragments/ui-legacy/auth/react-native/authenticator.mdx
  src/fragments/ui-legacy/auth/react/authenticator.mdx
  src/fragments/ui-legacy/auth/react/tutorial.mdx
  src/fragments/ui-legacy/interactions/react-native/chatbot.mdx
  src/fragments/ui/angular/configure-module-diff.mdx
  src/fragments/ui/angular/configure-module.mdx
  src/fragments/ui/auth/react-native/authenticator.mdx
  src/fragments/ui/auth/react/auth-state-management.mdx
  src/fragments/ui/auth/react/hiding-form-fields.mdx
  src/fragments/ui/interactions/react-native/chatbot.mdx
  src/fragments/ui/interactions/web/chatbot/usage.mdx
  src/fragments/ui/storage/react-native/s3-album.mdx
  src/fragments/ui/storage/react-native/s3-image.mdx
  src/fragments/ui/storage/web/s3-album.mdx
  src/fragments/ui/storage/web/s3-image-picker.mdx
  src/fragments/ui/storage/web/s3-image.mdx
  src/fragments/ui/storage/web/s3-text-picker.mdx
  src/fragments/ui/storage/web/s3-text.mdx
  src/fragments/ui/vue/configure-app-diff.mdx
  src/fragments/ui/vue/configure-app.mdx
  src/fragments/ui/vue/installation.mdx
Labels: amplify/js

#4179 feat: clear DataStore without first starting
  src/fragments/lib/datastore/js/other-methods.mdx
Labels: amplify/js

#4180 Update versions.ts
  src/constants/versions.ts
Labels: amplify/android

#3763 Added Angular & Ionic data binding examples
  src/fragments/ui/storage/web/s3-image.mdx
Labels: amplify/ui, first-time-contributor

#4189 docs(cli): specify "Cognito" groups for dynamic group authorization
  src/pages/cli-legacy/graphql-transformer/auth.mdx
  src/pages/cli/graphql/authorization-rules.mdx
Labels: amplify/cli

#4181 chore(native/geo): remove geo tagged cli setup
  src/fragments/lib/geo/android/getting_started/20_cli_resources.mdx
  src/fragments/lib/geo/ios/getting_started/20_cli_resources.mdx
Labels: amplify/ios, amplify/android

#4100 Create a custom Algolia search for docs
  adobe.d.ts
  amplify.yml
  next-env.d.ts
  next.config.js
  package.json
  public/scripts/docsearchv2_6_3.js
  src/components/Layout/index.tsx
  src/components/SearchBar/Autocomplete.tsx
  src/components/SearchBar/SearchItem.tsx
  src/components/SearchBar/functions/AutocompleteReshapeFunction.ts
  src/components/SearchBar/functions/groupBy.ts
  src/components/SearchBar/functions/index.ts
  src/components/SearchBar/functions/limit.ts
  src/components/SearchBar/functions/normalizeReshapeSources.ts
  src/components/SearchBar/functions/uniqBy.ts
  src/components/SearchBar/index.tsx
  src/components/SearchBar/types/Highlighted.ts
  src/components/SearchBar/types/ProductHit.ts
  src/components/SearchBar/types/index.ts
  src/components/TableOfContents/index.tsx
  src/pages/_app.tsx
  src/pages/cli/function/build-options.mdx
  src/pages/cli/graphql/overview.mdx
  src/pages/cli/migration/transformer-migration.mdx
  src/pages/cli/reference/files.mdx
  src/pages/cli/restapi/testing.mdx
  src/pages/cli/start/workflows.mdx
  src/pages/cli/teams/commands.mdx
  src/pages/cli/usage/containers.mdx
  src/pages/cli/usage/export-to-cdk.mdx
  src/pages/cli/usage/headless.mdx
  src/plugins/code-block.tsx
  src/plugins/headings.tsx
  src/plugins/import.tsx
  src/plugins/internal-link.tsx
  src/plugins/page.tsx
  src/styles/algolia.css
  tasks/build-algolia-search.mjs
  tasks/generate-sitemap.ts
  tasks/patch-next-scrolling.ts
  tsconfig.json
  yarn.lock
Labels: amplify/docs

#4210 Move indexes instead of deleting objects
  src/components/SearchBar/Autocomplete.tsx
  src/components/SearchBar/index.tsx
  tasks/build-algolia-search.mjs
Labels: docs-engineering

#4086 Get feedback module
  .github/actions/fetch_amplify_backend/action.yml
  .github/workflows/build.yml
  amplify.yml
  amplify/.config/project-config.json
  amplify/backend/api/submissions/cli-inputs.json
  amplify/backend/backend-config.json
  amplify/backend/function/submissionsLambda/amplify.state
  amplify/backend/function/submissionsLambda/custom-policies.json
  amplify/backend/function/submissionsLambda/function-parameters.json
  amplify/backend/function/submissionsLambda/lib/app.ts
  amplify/backend/function/submissionsLambda/lib/controllers/SubmissionsController.ts
  amplify/backend/function/submissionsLambda/lib/controllers/__mocks__/aws-sdk.ts
  amplify/backend/function/submissionsLambda/lib/controllers/__tests__/SubmissionsController.test.ts
  amplify/backend/function/submissionsLambda/lib/index.ts
  amplify/backend/function/submissionsLambda/lib/tsconfig.json
  amplify/backend/function/submissionsLambda/src/app.js
  amplify/backend/function/submissionsLambda/src/controllers/SubmissionsController.js
  amplify/backend/function/submissionsLambda/src/controllers/__mocks__/aws-sdk.js
  amplify/backend/function/submissionsLambda/src/controllers/__tests__/SubmissionsController.test.js
  amplify/backend/function/submissionsLambda/src/event.json
  amplify/backend/function/submissionsLambda/src/index.js
  amplify/backend/function/submissionsLambda/src/package.json
  amplify/backend/function/submissionsLambda/submissionsLambda-cloudformation-template.json
  amplify/backend/storage/submissionsTable/cli-inputs.json
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/cli.json
  build_support/create-test-profile.sh
  build_support/pull-environment.sh
  customHttp.yml
  jest.setup.js
  next.config.js
  package.json
  public/assets/thumbs-down.svg
  public/assets/thumbs-up.svg
  src/components/Feedback/__tests__/index.test.tsx
  src/components/Feedback/index.tsx
  src/components/Feedback/styles.tsx
  src/components/Menu/index.tsx
  src/pages/_document.tsx
  src/utils/track.ts
  yarn.lock
Labels: amplify/docs, docs-engineering

#4247 add note to point out that complex objects are not supported by DataS…
  src/pages/cli-legacy/graphql-transformer/storage.mdx
Labels: DataStore, amplify/codegen

#4254 Fix typo in Auth.fetchDevices JS snippet
  src/fragments/lib/auth/js/device_features/30_fetchDevice.mdx
Labels: amplify/js, auth

#4131 docs(cli): add project migration instructions
  src/directory/directory.js
  src/pages/cli/migration/cli-migrate-aws-account.mdx
Labels: amplify/cli
