Repository aws-amplify/docs, pull requests merged in 2022-10, with the labels that each got.

#3765 Remove commas that result in JSON syntax errors.
  src/fragments/lib/auth/native_common/existing_resources/common.mdx
Labels: first-time-contributor, external-contributor

#4704 docs: update preferred_username for override
  src/pages/cli/auth/override.mdx
Labels: amplify/cli, first-time-contributor

#4715 Update link in feature-flags.json
  src/components/FeatureFlags/feature-flags.json
Labels: first-time-contributor, external-contributor, hacktoberfest-accepted

#4707 update docs to match new Facebook UI
  src/fragments/lib/auth/common/social_signin_web_ui/configure_auth_category.mdx
Labels: amplify/android

#4476 fix: add section to clarify steps to update Cognito user email address with example
  src/fragments/lib/auth/js/manageusers.mdx
Labels: amplify/js

#4709 replace amplify framework by amplify
  Readme.md
  src/fragments/guides/location-service/setting-up-your-app-android.mdx
  src/fragments/guides/location-service/setting-up-your-app-ios.mdx
  src/fragments/lib/android-sdk.mdx
  src/fragments/lib/auth/js/enable_sign_in_sign_up.mdx
  src/fragments/lib/auth/js/getting-started.mdx
  src/fragments/lib/datastore/android/getting-started/60_initDataStore.mdx
  src/fragments/lib/datastore/flutter/getting-started/50_initDataStore.mdx
  src/fragments/lib/datastore/flutter/getting-started/60_initDataStore.mdx
  src/fragments/lib/geo/android/getting_started/40_init_geo.mdx
  src/fragments/lib/geo/ios/getting_started/40_init_geo.mdx
  src/fragments/lib/graphqlapi/ios/getting-started.mdx
  src/fragments/lib/graphqlapi/native_common/concepts.mdx
  src/fragments/lib/ios-sdk.mdx
  src/fragments/start/getting-started/angular/auth.mdx
  src/fragments/start/getting-started/react/auth.mdx
  src/fragments/start/getting-started/vanillajs/setup.mdx
  src/fragments/start/getting-started/vue/auth.mdx
  src/pages/index.tsx
  src/pages/lib/auth/getting-started/q/platform/[platform].mdx
  src/pages/lib/auth/mfa/q/platform/[platform].mdx
  src/pages/lib/auth/overview/q/platform/[platform].mdx
  src/pages/lib/auth/start/q/platform/[platform].mdx
  src/pages/lib/auth/switch-auth/q/platform/[platform].mdx
  src/pages/lib/graphqlapi/advanced-workflows/q/platform/[platform].mdx
  src/pages/lib/graphqlapi/authz/q/platform/[platform].mdx
  src/pages/lib/graphqlapi/concepts/q/platform/[platform].mdx
  src/pages/lib/interactions/chatbot/q/platform/[platform].mdx
  src/pages/lib/predictions/getting-started/q/platform/[platform].mdx
  src/pages/lib/predictions/sample/q/platform/[platform].mdx
  src/pages/lib/project-setup/prereq/q/platform/[platform].mdx
  src/pages/lib/push-notifications/getting-started/q/platform/[platform].mdx
  src/pages/lib/push-notifications/working-with-api/q/platform/[platform].mdx
  src/pages/lib/restapi/cancel/q/platform/[platform].mdx
  src/pages/lib/restapi/delete/q/platform/[platform].mdx
  src/pages/lib/restapi/fetch/q/platform/[platform].mdx
  src/pages/lib/restapi/update/q/platform/[platform].mdx
  src/pages/lib/storage/copy/q/platform/[platform].mdx
  src/pages/lib/storage/download/q/platform/[platform].mdx
  src/pages/lib/storage/list/q/platform/[platform].mdx
  src/pages/lib/storage/overview/q/platform/[platform].mdx
  src/pages/lib/storage/remove/q/platform/[platform].mdx
  src/pages/lib/storage/upload/q/platform/[platform].mdx
  src/pages/sdk/auth/working-with-api/q/platform/[platform].mdx
  src/pages/start/getting-started/auth/q/integration/[integration].mdx
  src/pages/start/getting-started/data-model/q/integration/[integration].mdx
  src/pages/start/getting-started/hosting/q/integration/[integration].mdx
  src/pages/start/getting-started/installation/q/integration/[integration].mdx
  src/pages/start/getting-started/nextsteps/q/integration/[integration].mdx
  src/pages/start/getting-started/setup/q/integration/[integration].mdx
  src/pages/start/q/integration/[integration].mdx
  src/pages/start/sample-apps/todo-app/q/integration/[integration].mdx
  tasks/build-algolia-search.mjs
Labels: first-time-contributor, external-contributor

#4740 docs(hub) add hub remove code snippet example
  src/fragments/lib/utilities/js/hub.mdx
Labels: pending-response
