Repository aws-amplify/docs, pull requests merged in 2022-12, with the labels that each got.

#4564 Document the format of config & credentails files
  src/pages/cli/reference/iam-roles-mfa.mdx
Labels: amplify/cli

#4909 added guide for using transfer acceleration with S3 bucket
  src/directory/directory.js
  src/fragments/lib/storage/js/transfer-acceleration.mdx
  src/fragments/lib/storage/js/upload.mdx
  src/pages/lib/storage/transfer-acceleration/q/platform/[platform].mdx
Labels: amplify/js

#4916 Search results
  src/components/SearchBar/Autocomplete.tsx
  src/components/SearchBar/functions/groupBy.ts
  tasks/build-algolia-search.mjs
Labels: docs-engineering

#4927 add run commands to library guide for React Native
  src/fragments/lib/project-setup/react-native/run-react-native.mdx
  src/fragments/lib/storage/js/upload.mdx
  src/fragments/start/getting-started/reactnative/integrate.mdx
  src/fragments/start/getting-started/reactnative/setup.mdx
Labels: amplify/js

#4917 Add codeql github workflow
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: docs-engineering

#4733 feat(cli): add populateOwnerFieldForStaticGroupAuth FF
  src/components/FeatureFlags/feature-flags.json
Labels: amplify/cli

#4932 Split cspell into its own workflow
  .github/workflows/build.yml
  .github/workflows/spellcheck.yml
Labels: docs-engineering

#4945 Add CSP to custtomhttp.yml
  customHttp.yml
  src/pages/_document.tsx
Labels: docs-engineering

#4416 fix: setup script for Windows
  build_support/create-awsconfig.mjs
  build_support/create-awsconfig.sh
  package.json
Labels: docs-engineering

#4590 clarify custom-roles.json
  src/pages/cli/graphql/authorization-rules.mdx
Labels: amplify/cli, amplify/data

#4948 fix: wrap angle brackets in curly braces
  src/fragments/lib/datastore/flutter/getting-started/10_preReq.mdx
  src/fragments/lib/storage/js/autotrack.mdx
  src/fragments/sdk/pubsub/android/getting-started.mdx
Labels: docs-engineering

#4930 feat: enable raw HTML strings in sidenav links
  src/components/Menu/Directory/index.tsx
  src/components/NextPrevious/index.tsx
Labels: docs-engineering

#4971 Added curly braces to JSON code block.
  src/pages/cli/usage/headless.mdx
Labels: first-time-contributor

#4962 fix: add bottom padding to menu so there is more room to scroll
  src/components/Menu/styles.tsx
Labels: amplify/docs-engineering

#4973 fix: add callout for delete mutation permissions
  src/pages/cli/graphql/authorization-rules.mdx
Labels: amplify/cli

#4967 block merging 'sudo' in content
  cspell.json
  src/fragments/lib-v1/project-setup/native_common/prereq/common_body.mdx
  src/fragments/lib/project-setup/flutter/platform-setup/platform-setup.mdx
Labels: amplify/docs-engineering, p0, ready-to-merge

#4599 chore(flutter): add snapcraft.yaml example in platform setup
  cspell.json
  src/fragments/lib/project-setup/flutter/platform-setup/platform-setup.mdx
Labels: amplify/flutter, pm-review-needed

#4961 (chore) - TOTP setup refactor
  src/fragments/lib/auth/js/mfa.mdx
Labels: amplify/js, pm-review-needed

#4985 Figma file update process
  public/images/console/ui-figma-import-error.png
  src/pages/console/uibuilder/figmatocode.mdx
Labels: amplify/studio
