Repository aws-amplify/docs, pull requests merged in 2023-01, with the labels that each got.

#4991 updated hub message payload
  src/fragments/lib/graphqlapi/js/subscribe-data.mdx
  src/fragments/lib/pubsub/js/subunsub.mdx
  src/fragments/lib/utilities/js/hub.mdx
Labels: amplify/js, API GraphQL, PubSub

#4780 Add Auth Pinpoint events to Amplify docs, not just SDK
  src/fragments/lib-v1/analytics/android/record.mdx
  src/fragments/lib-v1/analytics/ios/record.mdx
  src/fragments/lib-v1/analytics/native_common/getting-started/auth-events.mdx
  src/fragments/lib/analytics/android/record.mdx
  src/fragments/lib/analytics/ios/record.mdx
Labels: amplify/ios, amplify/android, pending-response

#4978 Update Android SDK versions post-release
  src/constants/versions.ts
Labels: amplify/android

#4994 create a task that will scan all mdx files for A tags
  tasks/check-link-tags.mjs
Labels: amplify/docs-engineering

#5051 Update CODEOWNERS to be the documentation team only
  .github/CODEOWNERS
Labels: amplify/docs-engineering

#5050 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: amplify/docs-engineering

#4996 Fixing spacing issues
  src/fragments/lib-v1/auth/ios/password_management/10_reset_password.mdx
  src/fragments/lib/auth/ios/password_management/10_reset_password.mdx
  src/fragments/lib/utilities/js/hub.mdx
Labels: amplify/js

#5048 Update versions.ts
  src/constants/versions.ts
Labels: amplify/docs-engineering

#4975 fix: h4 margin for prev/next buttons
  src/components/NextPrevious/styles.tsx
Labels: amplify/docs-engineering

#5042 fix(docs): Remove lifecycle viewmodel from setup
  src/fragments/start/getting-started/android/setup.mdx
Labels: amplify/android

#5022 add github workflow to run the link tag check script on each PR
  .github/workflows/tagcheck.yml
Labels: amplify/docs-engineering

#5060 Update versions.ts
  src/constants/versions.ts
Labels: amplify/android

#5062 chore: add resolutions for 'decode-uri-component' and 'json5'
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5063 fix(js, ios, android, flutter, react native) added individual callouts to device tracking feature requests
  src/fragments/lib/auth/android/device_features/40_trackDevice.mdx
  src/fragments/lib/auth/common/device_features/common.mdx
  src/fragments/lib/auth/flutter/device_features/40_trackDevice.mdx
  src/fragments/lib/auth/ios/device_features/40_trackDevice.mdx
  src/fragments/lib/auth/js/device_features/40_trackDevice.mdx
Labels: amplify/js, amplify/ios, amplify/android, amplify/flutter, react-native

#5004 There were many extra ')' in this page
  src/fragments/lib/graphqlapi/js/query-data.mdx
Labels: amplify/js, external-contributor
