Repository aws-amplify/docs, pull requests merged in 2023-05, with the labels that each got.

#5442 fix(flutter): Add platform-specific changes to migration guide
  src/fragments/lib/project-setup/flutter/upgrade-guide/upgrade-guide.mdx
Labels: amplify/flutter, ready-to-merge

#5430 feat: add permissions boundary example
  src/pages/cli/project/permissions-boundary.mdx
Labels: amplify/cli

#5417 fix: unlink storage resource info
  src/pages/cli/storage/import.mdx
Labels: amplify/cli

#5446 removed Flutter from connect to the cloud
  src/directory/directory.mjs
Labels: amplify/flutter

#5443 fix: remove docs around a DEV environment for Amplify Hosting
  src/pages/cli/hosting/hosting.mdx
Labels: amplify/cli

#5440 fix(JS): Update FAQ for Storage.get()
  src/fragments/lib/storage/js/download.mdx
  yarn.lock
Labels: amplify/js, ready-to-merge

#5438 feat: (pending-release) adds info on multiSelect workflow for mock and functions
  src/pages/cli/usage/mock.mdx
Labels: amplify/cli

#5437 feat: add multi split schema mitigation instructions
  src/pages/console/data/data-model.mdx
Labels: amplify/studio

#5390 Put Amplify Hosting in the same list as CLI in tutorial
  src/pages/start/q/integration/[integration].mdx
Labels: amplify/docs-engineering

#5451 chore(flutter): note Kotlin version requirement in Android guide
  src/fragments/lib/project-setup/flutter/platform-setup/android.mdx
Labels: amplify/flutter, ready-to-merge

#5453 fix(Android): Fix for documentation to properly handle usernotconfirmedexception
  src/fragments/lib-v1/auth/native_common/signin_next_steps/common.mdx
  src/fragments/lib/auth/android/signin_next_steps/10_signin.mdx
  src/fragments/lib/auth/android/signin_next_steps/40_confirm_new_password.mdx
  src/fragments/lib/auth/android/signin_next_steps/50_reset_password.mdx
Labels: amplify/android, ready-to-merge

#5454 updated intro for libraries
  src/fragments/lib-v1/flutter.mdx
  src/fragments/lib/flutter.mdx
  src/pages/lib-v1/q/platform/[platform].mdx
  src/pages/lib/q/platform/[platform].mdx
Labels: amplify/flutter, ready-to-merge

#5458 Add new adobe analytics
  customHttp.yml
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: amplify/docs-engineering

#5434 feat(android): Add Authenticator callout to Android docs as well
  cspell.json
  src/fragments/lib/auth/android/getting_started/05_authenticatorCallout.mdx
  src/fragments/lib/auth/android/getting_started/45_authenticator.mdx
  src/fragments/lib/auth/native_common/getting_started/common.mdx
Labels: amplify/android

#5424 fix: highlights, formatting and others on studio
  src/pages/console/adminui/access-management.mdx
  src/pages/console/data/content-management.mdx
  src/pages/console/formbuilder/customize.mdx
  src/pages/console/formbuilder/lifecycle.mdx
  src/pages/console/formbuilder/overrides.mdx
  src/pages/console/tutorial/bindui.mdx
  src/pages/console/tutorial/buildui.mdx
  src/pages/console/tutorial/collections.mdx
  src/pages/console/tutorial/data.mdx
  src/pages/console/uibuilder/figmatocode.mdx
  src/pages/console/uibuilder/override.mdx
  src/pages/console/uibuilder/responsive.mdx
Labels: amplify/studio

#5455 Update switch-auth.mdx
  src/fragments/lib/auth/js/switch-auth.mdx
Labels: amplify/js, amplify/auth

#5433 fix(JS): Update Angular Getting Started tutorial with proper schema and file references
  src/fragments/start/getting-started/angular/data-model.mdx
Labels: amplify/js, ready-to-merge

#4893 Updating documentation for next for SSG
  cspell.json
  src/fragments/guides/hosting/nextjs.mdx
Labels: first-time-contributor, amplify/hosting, external-contributor

#5463 chore: Add instructions on using Next.js App Router
  src/fragments/lib/ssr/js/getting-started.mdx
Labels: amplify/js

#5447 chore(flutter): clarify the purpose of validateObjectExistence flag of the getUrl API
  src/fragments/lib/storage/flutter/download.mdx
  src/fragments/lib/storage/js/download.mdx
Labels: amplify/js, amplify/flutter, ready-to-merge

#5427 feat(predictions): add amplify-swift predictions v2 documentation
  src/directory/directory.mjs
  src/fragments/lib/predictions/ios/escapehatch.mdx
  src/fragments/lib/predictions/ios/getting-started/30_installLib.mdx
  src/fragments/lib/predictions/ios/getting-started/40_init.mdx
  src/fragments/lib/predictions/ios/getting-started/50_translate.mdx
  src/fragments/lib/predictions/ios/identify-entity.mdx
  src/fragments/lib/predictions/ios/identify-text.mdx
  src/fragments/lib/predictions/ios/interpret.mdx
  src/fragments/lib/predictions/ios/label-image.mdx
  src/fragments/lib/predictions/ios/text-speech.mdx
  src/fragments/lib/predictions/ios/transcribe.mdx
  src/fragments/lib/predictions/ios/translate.mdx
  src/fragments/start/getting-started/ios/nextsteps.mdx
Labels: amplify/ios

#5464 feat: adds index directive limitation and callout
  src/pages/console/data/data-model.mdx
Labels: amplify/studio, technical-review-needed

#5466 chore(JS): callout for Push Notification migration guide
  src/fragments/lib/push-notifications/react-native/migrate-from-previous-version.mdx
Labels: amplify/js, ready-to-merge

#5452 chore(CLI): Block switcher for admin actions
  src/pages/cli/auth/admin.mdx
Labels: amplify/cli

#5450 feat: Multi select mock and functions
  src/pages/cli/usage/mock.mdx
Labels: amplify/cli

#5428 docs(graphql): add sample code reference to cli iam auth section
  src/pages/cli/graphql/authorization-rules.mdx
Labels: amplify/data

#5305 Add DynamoDB config parameters override samples
  src/pages/cli/graphql/override.mdx
Labels: amplify/cli

#5469 Update Amplify Android versions
  src/constants/versions.ts
Labels: amplify/android, product-owner-review-needed, technical-review-needed

#5483 update vm2
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5484 update dev preview mention
  src/fragments/lib/project-setup/flutter/prereq/prereq.mdx
Labels: amplify/flutter, ready-to-merge

#5487 chore: remove stale explanations from aws-exports.js file reference
  src/pages/cli/reference/files.mdx
Labels: amplify/cli

#5482 feat: add limitation on figma to code
  src/pages/console/adminui/extend-cli.mdx
  src/pages/console/uibuilder/figmatocode.mdx
Labels: amplify/studio

#5478 docs(predictions): make sure refer Predictions class before using it
  src/fragments/lib/predictions/js/getting-started.mdx
Labels: amplify/js, ready-to-merge, react-native

#4340 Addresses aws-amplify/admin-ui#443
  src/pages/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/[platform].mdx
Labels: amplify/studio, product-owner-review-needed, technical-review-needed

#5334 redesigned feedback component and mobile secondary nav
  next.config.mjs
  package.json
  preset.js
  public/assets/contents.svg
  src/components/FeedbackSticky/__tests__/index.test.tsx
  src/components/FeedbackSticky/index.tsx
  src/components/FeedbackSticky/styles.tsx
  src/components/Footer/index.tsx
  src/components/Layout/index.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.tsx
  src/components/MobileMenuIcons/index.tsx
  src/components/MobileMenuIcons/styles.tsx
  src/components/Page/index.tsx
  src/components/Page/metaContent.tsx
  src/components/Page/styles.tsx
  src/components/TableOfContents/index.tsx
  src/components/TableOfContents/styles.tsx
  src/constants/img.ts
  src/pages/ChooseFilterPage.tsx
  yarn.lock
Labels: amplify/docs-engineering

#5505 fix: mobile secondary nav overlap fix
  src/components/Menu/styles.tsx
Labels: amplify/docs-engineering

#5501 chore(Flutter): Amplify Flutter API subscription reconnection guide
  src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx
Labels: amplify/flutter, ready-to-merge

#5498 fix-(React Native): update React Native dependency installations
  src/fragments/lib/auth/js/getting-started-steps-basic-auth-react-native.mdx
  src/fragments/lib/react-native-polyfills.mdx
  src/fragments/start/getting-started/reactnative/setup.mdx
Labels: amplify/js

#5495 Misc. docs engineering improvements
  src/components/Card/styles.tsx
  src/components/Menu/Directory/index.tsx
  src/components/Menu/VersionSwitcher/index.tsx
Labels: amplify/docs-engineering
