Repository aws-amplify/docs, pull requests merged in 2023-07, with the labels that each got.

#5616 Addresses #5604
  src/pages/cli-legacy/graphql-transformer/relational.mdx
Labels: amplify/data, ready-to-merge

#5613 Amplify Android: replace deprecated id with identifier method
  src/fragments/lib-v1/datastore/android/data-access/delete-snippet.mdx
  src/fragments/lib-v1/datastore/android/data-access/update-snippet.mdx
  src/fragments/lib-v1/datastore/android/relational/delete-snippet.mdx
  src/fragments/lib/datastore/android/data-access/delete-snippet.mdx
  src/fragments/lib/datastore/android/data-access/update-snippet.mdx
  src/fragments/lib/datastore/android/relational/delete-snippet.mdx
Labels: amplify/android

#5566 chore(JS): Add confirmSignIn() flows to JS sign in docs
  src/fragments/lib/auth/js/emailpassword.mdx
Labels: amplify/js, ready-to-merge

#5429 Fix Vue tutorial - latest npm init vue doesn't require the vite.config.js updates
  src/fragments/start/getting-started/vue/setup.mdx
Labels: amplify/js, ready-to-merge

#5587 Add TS examples for getting-started pages of the Auth category
  src/fragments/lib/auth/js/emailpassword.mdx
  src/fragments/ui/auth/react/withauthenticator.mdx
Labels: amplify/js, first-time-contributor, external-contributor, ready-to-merge

#5612 added aria-label to the search box
  src/components/SearchBar/index.tsx
Labels: amplify/docs-engineering

#5628 Revert aa order
  amplify.yml
  customHttp.yml
  next.config.mjs
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: amplify/docs-engineering

#5602 feat(data): update code examples for optimistic UI docs - update types, update return value for mutation hooks, and add additional cache invalidation
  src/fragments/lib/graphqlapi/js/optimistic-ui.mdx
Labels: amplify/js, guides, example, docs, amplify/data, API GraphQL, ready-to-merge, technical-review-needed

#5621 fix: Amplify Flutter Datastore save example. Remove extraneous import…
  src/fragments/lib/datastore/flutter/data-access/save-snippet.mdx
Labels: amplify/flutter, ready-to-merge

#5611 fix(storage): Add information about request options
  src/fragments/lib/storage/ios/list.mdx
Labels: amplify/ios

#5608 update swift storage escape hatch SDK documentation links
  src/fragments/lib/storage/ios/escapehatch.mdx
Labels: amplify/ios

#5607 update swift storage category upload
  src/fragments/lib/storage/ios/upload.mdx
Labels: amplify/ios

#5643 add contribute getting-started page to directory
  generatePathMap.cjs.js
Labels: amplify/docs-engineering

#5647 fix(JS): Call out for expires param when calling Storage.get()
  src/fragments/lib/storage/js/download.mdx
Labels: amplify/js, ready-to-merge

#5644 feat(storage): supporting put api when the objectLock is enabled
  src/fragments/lib/storage/js/getting-started.mdx
Labels: amplify/js, ready-to-merge

#5640 update userID code snippet for Push Notifications and Flutter
  src/fragments/lib/push-notifications/flutter/identify_user/10_get_auth_user.mdx
Labels: amplify/flutter, ready-to-merge

#5650 Provides recommendation to isolate Amplify workloads by account
  src/pages/console/adminui/start.mdx
Labels: amplify/studio, product-owner-review-needed, technical-review-needed

#5655 fix(auth): Added documentation for how to handle notauthorized exceptions when fail lambda is true
  src/fragments/lib/auth/android/signin_next_steps/30_confirm_custom_challenge.mdx
  src/fragments/lib/auth/flutter/signin_with_custom_flow/40_custom_challenge.mdx
  src/fragments/lib/auth/ios/signin_next_steps/30_confirm_custom_challenge.mdx
Labels: amplify/ios, amplify/android, amplify/flutter, ready-to-merge

#5663 Update puppeteer
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5658 fix (JS): add callout for MQTT limitation and fix code example to eliminate compilation error
  src/fragments/lib/auth/js/emailpassword.mdx
  src/fragments/lib/pubsub/js/getting-started.mdx
Labels: amplify/js, ready-to-merge

#5648 update(JS): Callout for progressCallback event handler
  src/fragments/lib/storage/js/upload.mdx
Labels: amplify/js, ready-to-merge

#5620 Added ts examples for Password & user management in the Auth Category
  src/fragments/lib/auth/js/manageusers.mdx
Labels: amplify/js, external-contributor, ready-to-merge

#5671 add cron schedule to link checker workflow
  .github/workflows/check_for_broken_links.yml
Labels: amplify/docs-engineering

#5665 feat(flutter): Add `federateToIdentityPool` docs
  src/directory/directory.mjs
  src/fragments/lib/auth/flutter/advanced/advanced.mdx
  src/pages/lib/auth/advanced/q/platform/[platform].mdx
Labels: amplify/flutter, ready-to-merge

#5603 Add typescript examples for Social sign-in Oauth (react/react-native)
  src/fragments/lib/auth/js/react-native-social.mdx
  src/fragments/lib/auth/js/react-native-withoauth.mdx
  src/fragments/lib/auth/js/social.mdx
Labels: amplify/js, external-contributor, ready-to-merge, react-native

#5679 fix: add callout on oauth properties in aws-exports
  src/pages/cli/auth/import.mdx
Labels: amplify/cli

#5624 Feat/mfa ts samples
  src/fragments/lib/auth/js/mfa.mdx
Labels: amplify/js, external-contributor, ready-to-merge

#5674 Update index.mdx
  src/pages/cli/index.mdx
Labels: amplify/cli, first-time-contributor, external-contributor

#5625 Feat/switch auth flows ts samples
  src/fragments/lib/auth/js/switch-auth.mdx
Labels: amplify/js, external-contributor, ready-to-merge

#5686 Update alt text for decorative images
  src/components/FeaturesGrid/index.tsx
  src/components/Footer/index.tsx
  src/components/LinkBanner/index.tsx
  src/components/Menu/FilterSelect/index.tsx
  src/components/Menu/RepoActions/index.tsx
  src/components/NextPrevious/index.tsx
  src/pages/index.tsx
Labels: amplify/docs-engineering

#5675 feat(flutter): Add auth next steps
  src/directory/directory.mjs
  src/fragments/lib/auth/flutter/signin_next_steps/10_signin.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/20_confirm_sms_mfa.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/30_confirm_custom_challenge.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/40_confirm_new_password.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/50_reset_password.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/60_confirm_signup.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/70_done.mdx
  src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
  src/pages/lib/auth/signin_next_steps/q/platform/[platform].mdx
Labels: amplify/flutter, ready-to-merge

#5688 feat(cli): add codegen timeout scenario for pull failure
  cspell.json
  src/pages/cli/project/troubleshooting.mdx
Labels: external-contributor, ready-to-merge

#5666 fix: Bump Android versions; add multipart upload docs from other platforms
  src/constants/versions.ts
  src/fragments/lib/storage/android/upload.mdx
Labels: amplify/android, product-owner-review-needed

#5694 chore(JS/Storage): remove solved issue from FAQs
  src/fragments/lib/storage/js/download.mdx
Labels: ready-to-merge

#5709 fix(misc): Fix the link to aws sdk for kotlin
  src/fragments/lib/android-escape-hatch-warning.mdx
Labels: amplify/android
