Repository aws-amplify/docs, pull requests merged in 2023-08, with the labels that each got.

#5710 chore(logging): Add pre-req for amplify version
  src/fragments/lib/logging/android/setup_logging/10_pre_req.mdx
  src/fragments/lib/logging/ios/setup_logging/10_pre_req.mdx
  src/fragments/start/getting-started/android/nextsteps.mdx
  src/fragments/start/getting-started/ios/nextsteps.mdx
Labels: ready-to-merge

#5700 fix: broken studio links
  src/pages/console/data/data-model.mdx
  src/pages/console/formbuilder/data-binding.mdx
  src/pages/console/formbuilder/overview.mdx
  src/pages/console/formbuilder/special-inputs.mdx
Labels: amplify/studio

#5695 Use aria-label to give more descriptive text for screen reader
  src/components/Menu/RepoActions/index.tsx
Labels: amplify/docs-engineering

#5685 Fix Flutter Datastore QueryPredicates
  src/fragments/lib-v1/datastore/android/data-access/query-predicate-types.mdx
  src/fragments/lib-v1/datastore/android/sync/10-installPlugin.mdx
  src/fragments/lib-v1/datastore/flutter/data-access/query-predicate-types.mdx
  src/fragments/lib-v1/datastore/flutter/sync/10-installPlugin.mdx
  src/fragments/lib-v1/datastore/ios/data-access/query-predicate-types.mdx
  src/fragments/lib-v1/datastore/ios/sync/10-installPlugin.mdx
  src/fragments/lib-v1/datastore/native_common/callout/datastore-auth-rules-cli.mdx
  src/fragments/lib-v1/datastore/native_common/data-access.mdx
  src/fragments/lib-v1/datastore/native_common/setup-auth-rules.mdx
  src/fragments/lib/datastore/android/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/android/sync/10-installPlugin.mdx
  src/fragments/lib/datastore/flutter/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/flutter/sync/10-installPlugin.mdx
  src/fragments/lib/datastore/ios/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/ios/sync/10-installPlugin.mdx
  src/fragments/lib/datastore/js/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/native_common/callout/datastore-auth-rules-cli.mdx
  src/fragments/lib/datastore/native_common/data-access.mdx
  src/fragments/lib/datastore/native_common/setup-auth-rules.mdx
Labels: amplify/flutter

#5645 TS samples for "Auth events", "Remember a device" and "Delete user" pages
  src/fragments/lib/auth/js/delete_user.mdx
  src/fragments/lib/auth/js/device_features/10_rememberDevice.mdx
  src/fragments/lib/auth/js/device_features/20_forgetDevice.mdx
  src/fragments/lib/auth/js/device_features/30_fetchDevice.mdx
  src/fragments/lib/auth/js/hub_events/10_listen_events.mdx
Labels: external-contributor, ready-to-merge

#5705 show the installation command for prereq
  src/fragments/lib/project-setup/ios/prereq/prereq.mdx
  src/fragments/lib/project-setup/native_common/prereq/common_body.mdx
  src/fragments/start/getting-started/common/prereq.mdx
Labels: amplify/cli, amplify/js, amplify/ios, amplify/android, amplify/flutter

#5693 fix: upgrade API GraphQL migration guide
  src/pages/lib/graphqlapi/upgrade-guide/q/platform/[platform].mdx
Labels: amplify/js, product-owner-review-needed, ready-to-merge

#5723 updated auth flows code grant link
  src/fragments/lib-v1/auth/native_common/signin_web_ui/common.mdx
  src/fragments/lib/auth/native_common/signin_web_ui/common.mdx
Labels: amplify/js, amplify/ios, amplify/android, amplify/flutter, amplify/auth

#5722 fix(misc): Fix for missing or incorrect accessibility text in some images in Android documentation
  src/fragments/lib-v1/debugging/android/dev-menu/usage.mdx
  src/fragments/lib-v1/project-setup/android/create-application/10_createProject.mdx
  src/fragments/lib-v1/project-setup/android/create-application/20_gradle.mdx
  src/fragments/lib-v1/project-setup/android/use-existing-resources/use-existing-resources.mdx
  src/fragments/lib/debugging/android/dev-menu/usage.mdx
  src/fragments/lib/project-setup/android/create-application/10_createProject.mdx
  src/fragments/lib/project-setup/android/create-application/20_gradle.mdx
  src/fragments/lib/project-setup/android/use-existing-resources/use-existing-resources.mdx
  src/fragments/lib/push-notifications/android/setup_push_service/setup-fcm.mdx
  src/fragments/sdk/analytics/android/getting-started.mdx
  src/fragments/sdk/api/android/graphql.mdx
  src/fragments/sdk/pubsub/android/getting-started.mdx
  src/fragments/sdk/storage/android/transfer-utility.mdx
  src/fragments/start/getting-started/android/add-api.mdx
  src/fragments/start/getting-started/android/setup.mdx
  src/fragments/start/sample-apps/android/todo-app.mdx
Labels: amplify/android, product-owner-review-needed

#5729 Add resolution for proxy-agent
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5734 Fix datastore predicates
  src/fragments/lib-v1/datastore/android/data-access/query-predicate-types.mdx
  src/fragments/lib-v1/datastore/flutter/data-access/query-predicate-types.mdx
  src/fragments/lib-v1/datastore/ios/data-access/query-predicate-types.mdx
  src/fragments/lib-v1/datastore/native_common/data-access.mdx
  src/fragments/lib/datastore/android/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/flutter/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/ios/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/js/data-access/query-predicate-types.mdx
  src/fragments/lib/datastore/native_common/data-access.mdx
Labels: amplify/flutter

#5727 feat: add troubleshooting info and limitations for studio
  src/pages/console/adminui/extend-cli.mdx
Labels: amplify/studio

#5622 feat: Add callout for Pinpoint event delay
  src/fragments/lib-v1/analytics/android/record.mdx
  src/fragments/lib-v1/analytics/flutter/record.mdx
  src/fragments/lib-v1/analytics/ios/record.mdx
  src/fragments/lib/analytics/android/getting-started/40_record.mdx
  src/fragments/lib/analytics/android/record.mdx
  src/fragments/lib/analytics/flutter/record.mdx
  src/fragments/lib/analytics/ios/record.mdx
  src/fragments/lib/analytics/js/record.mdx
Labels: amplify/flutter, technical-review-needed

#5730 Dependabot updates
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5733 fix(RN, JS): remove RN fragment, add callout for Auth.getPreferredMFA()
  src/fragments/lib/auth/js/mfa.mdx
  src/pages/lib/auth/mfa/q/platform/[platform].mdx
Labels: amplify/js, ready-to-merge

#5741 Next image
  .gitignore
  next.config.mjs
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: amplify/docs-engineering

#5720 remove platform pages that have an ending slash
  tasks/link-checker.js
Labels: amplify/docs-engineering

#5761 Update amplify-cli-core to 4.2.4
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5760 Remove react native connect to the cloud tutorial
  public/images/lib/getting-started/flutter/add-api-add-authentication-deploy.png
  public/images/lib/getting-started/flutter/add-api-add-authentication-sidebar.png
  public/images/lib/getting-started/reactnative/add-api-verify-sync-create-todo.png
  public/images/lib/getting-started/reactnative/add-api-verify-sync-inspect-items.png
  public/images/lib/getting-started/reactnative/add-api-verify-sync-save-todo.png
  public/images/lib/getting-started/reactnative/add-api-verify-sync-sidebar.png
  public/images/lib/getting-started/reactnative/connect-to-cloud-create-app-backend.png
  public/images/lib/getting-started/reactnative/connect-to-cloud-open-amplify-studio.png
  public/images/lib/getting-started/reactnative/local-setup-instructions.png
  src/fragments/start/getting-started/reactnative/add-api.mdx
  src/pages/start/getting-started/add-api/q/integration/[integration].mdx
Labels: redirects-needed, deleted-assets

#5421 feat: text highlight improvements for error, success and warnings
  src/plugins/cli-error-language.tsx
  src/plugins/code-block.tsx
  src/styles/prism-language-error.css
  src/styles/styles.css
Labels: amplify/docs-engineering, ready-to-merge

#5750 Auth-jtbd-update-abdallah
  src/directory/directory.mjs
  src/fragments/lib/auth/js/enable-signin-signup-signout.mdx
  src/fragments/lib/auth/js/set-up-auth.mdx
  src/pages/lib/auth/enable_signup_signin_signout/q/platform/[platform].mdx
Labels: amplify/auth

#5779 Update spellcheck command to use --no-progress flag
  package.json
Labels: amplify/docs-engineering

#5769 Youtube embed component
  cspell.json
  src/components/YoutubeEmbed/YoutubeEmbed.tsx
  src/components/YoutubeEmbed/index.ts
  src/components/contribute/QuickstartResources.tsx
  src/fragments/cli-config.mdx
  src/fragments/guides/hosting/custom-domains.mdx
  src/fragments/guides/hosting/nextjs.mdx
  src/fragments/guides/hosting/password-protected-deployments.mdx
  src/fragments/guides/hosting/pull-request-previews.mdx
  src/fragments/lib-v1/datastore/native_common/how-it-works.mdx
  src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
  src/fragments/lib/datastore/native_common/how-it-works.mdx
  src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx
  src/pages/console/uibuilder/bestpractices.mdx
  src/plugins/import.tsx
Labels: amplify/docs-engineering

#5759 Switcher
  src/components/Menu/FilterSelect/index.tsx
  src/components/Menu/FilterSelect/styles.tsx
  src/utils/filter-data.ts
Labels: amplify/docs-engineering

#5738 TS examples for Sign In confirmation
  src/fragments/lib/auth/js/emailpassword.mdx
Labels: amplify/js, ready-to-merge

#5772 fix:update the import in admin auth example
  src/pages/cli/auth/admin.mdx
Labels: amplify/cli

#5649 feat(swift): iOS Working With Files - Optimistic UI - Upgrade guide for AppSync SDK
  cspell.json
  src/directory/directory.mjs
  src/fragments/lib/graphqlapi/ios/optimistic-ui.mdx
  src/fragments/lib/graphqlapi/ios/upgrade-guide.mdx
  src/fragments/lib/graphqlapi/ios/working-with-files.mdx
  src/fragments/lib/graphqlapi/js/upgrade-guide.mdx
  src/pages/lib/graphqlapi/optimistic-ui/q/platform/[platform].mdx
  src/pages/lib/graphqlapi/upgrade-guide/q/platform/[platform].mdx
  src/pages/lib/graphqlapi/working-with-files/q/platform/[platform].mdx
Labels: amplify/data, product-owner-review-needed

#5584 Update the switcher for Auth resources set up
  src/fragments/lib/auth/js/getting_started/10_setUpBackendResources.mdx
Labels: amplify/js, p3, ready-to-merge

#5764 chore: added alt text for the images in the flutter library docs
  src/fragments/cli-config.mdx
  src/fragments/lib-v1/datastore/native_common/how-it-works.mdx
  src/fragments/lib/auth/common/device_features/common.mdx
  src/fragments/lib/auth/common/sms/flows.mdx
  src/fragments/lib/auth/common/social_signin_web_ui/configure_auth_category.mdx
  src/fragments/lib/auth/common/social_signin_web_ui/setup_auth_provider.mdx
  src/fragments/lib/auth/flutter/signin_web_ui/20_platform_specific_setup.mdx
  src/fragments/lib/datastore/native_common/how-it-works.mdx
  src/fragments/lib/project-setup/flutter/platform-setup/ios.mdx
  src/fragments/lib/project-setup/flutter/platform-setup/macos.mdx
  src/fragments/lib/push-notifications/android/setup_push_service/setup-fcm.mdx
  src/fragments/lib/push-notifications/common/enable-rich-notifications.mdx
  src/fragments/lib/push-notifications/common/interact_with_notifications/notification-lifecycle.mdx
  src/fragments/lib/push-notifications/ios/getting_started/ios-set-entitlements.mdx
  src/fragments/lib/storage/flutter/upload.mdx
Labels: amplify/flutter, web accessibility

#5718 JTBD Expander Component
  src/components/Accordion/icons.tsx
  src/components/Accordion/index.tsx
  src/components/Accordion/styles.tsx
  src/components/BlockSwitcher/index.tsx
  src/components/TableOfContents/index.tsx
  src/plugins/import.tsx
  src/utils/traverseHeadings.ts
Labels: amplify/docs-engineering

#5783 Remove unneeded JS from pages
  package.json
  src/components/UiComponentProps/index.tsx
  src/constants/strings.ts
  src/pages/cli/reference/feature-flags.mdx
  src/plugins/import.tsx
  src/utils/traverseHeadings.ts
  yarn.lock
Labels: amplify/docs-engineering

#5788 JTBD Expander Metrics Tracking
  src/components/Accordion/index.tsx
  src/utils/track.ts
Labels: amplify/docs-engineering

#5796 Should say "called" instead of "canned" on function build options page
  src/pages/cli/function/build-options.mdx
Labels: amplify/cli

#5805 update link scanning workflow
  .github/workflows/check_for_broken_links.yml
  tasks/link-checker.js
Labels: amplify/docs-engineering

#5778 feedback component v2
  jest.setup.js
  next.config.mjs
  package.json
  preset.js
  src/components/ExternalLink/index.tsx
  src/components/Feedback/__tests__/index.test.tsx
  src/components/Feedback/index.tsx
  src/components/Feedback/styles.tsx
  src/components/FeedbackSticky/__tests__/index.test.tsx
  src/components/FeedbackSticky/index.tsx
  src/components/FeedbackSticky/styles.tsx
  src/components/Icons/CloseIcon.tsx
  src/components/Icons/ExternalLinkIcon.tsx
  src/components/Icons/MenuIcon.tsx
  src/components/Icons/TOCIcon.tsx
  src/components/Icons/ThumbsDown.tsx
  src/components/Icons/ThumbsDownFilled.tsx
  src/components/Icons/ThumbsUp.tsx
  src/components/Icons/ThumbsUpFilled.tsx
  src/components/Icons/index.tsx
  src/components/Menu/__tests__/Menu.test.tsx
  src/components/Menu/index.tsx
  src/components/MobileMenuIcons/index.tsx
  src/components/Page/metaContent.tsx
  src/components/TableOfContents/index.tsx
  yarn.lock
Labels: amplify/docs-engineering

#5792 add component deletion info
  public/images/studio/buildui/delete-components.png
  public/images/studio/buildui/edit-ui-library.png
  public/images/studio/buildui/multiple-components-selection.png
  src/pages/console/tutorial/buildui.mdx
Labels: amplify/studio

#5816 chore: add callout to flutter credentials page
  src/fragments/lib/auth/flutter/managing_credentials/10_managing_credentials.mdx
Labels: amplify/flutter, ready-to-merge

#5808 Image sizes
  src/components/ExternalLink/index.tsx
  src/components/Footer/index.tsx
  src/components/Menu/RepoActions/index.tsx
  src/components/NextPrevious/index.tsx
  src/styles/elements.css
Labels: amplify/docs-engineering

#5690 feat(Auth): Adding documentation for TOTP support
  src/directory/directory.mjs
  src/fragments/lib/auth/common/mfa/add_mfa.mdx
  src/fragments/lib/auth/common/mfa/flows.mdx
  src/fragments/lib/auth/common/mfa/update_mfa.mdx
  src/fragments/lib/auth/common/sms/flows.mdx
  src/fragments/lib/auth/flutter/signin_next_steps/10_signin.mdx
  src/fragments/lib/auth/ios/mfa_preference/10_fetch_mfa_preference.mdx
  src/fragments/lib/auth/ios/mfa_preference/20_update_mfa_preference.mdx
  src/fragments/lib/auth/ios/signin_next_steps/100_continue_mfa_setup.mdx
  src/fragments/lib/auth/ios/signin_next_steps/10_signin.mdx
  src/fragments/lib/auth/ios/signin_next_steps/80_confirm_totp_mfa.mdx
  src/fragments/lib/auth/ios/signin_next_steps/90_continue_mfa_selection_intro.mdx
  src/fragments/lib/auth/ios/signin_next_steps/91_continue_mfa_selection_code.mdx
  src/fragments/lib/auth/ios/sms/confirm_sign_in.mdx
  src/fragments/lib/auth/ios/sms/confirm_sign_up.mdx
  src/fragments/lib/auth/ios/sms/sign_in.mdx
  src/fragments/lib/auth/ios/sms/sign_up.mdx
  src/fragments/lib/auth/ios/totp/confirm_sign_in.mdx
  src/fragments/lib/auth/ios/totp/set_up_totp.mdx
  src/fragments/lib/auth/ios/totp/sign_in.mdx
  src/fragments/lib/auth/ios/totp/verify_totp_setup.mdx
  src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
  src/pages/lib/auth/mfa/q/platform/[platform].mdx
  src/pages/lib/auth/sms_flows/q/platform/[platform].mdx
Labels: amplify/ios, ready-to-merge

#5786 chore (Studio): Add Block Start Account Switch To Main Amplify Page
  src/components/ExternalLinkButton/index.tsx
  src/components/InternalLinkButton/index.tsx
  src/pages/console/adminui/start.mdx
  src/pages/console/index.mdx
  src/plugins/import.tsx
  src/styles/link-button-styles.tsx
Labels: amplify/studio, technical-review-needed

#5825 Amplify Android Release 2.13.0
  src/constants/versions.ts
Labels: amplify/android

#5832 wrap link retrieval in try/catch
  tasks/link-checker.js
Labels: amplify/docs-engineering
