Repository aws-amplify/docs, pull requests merged in 2023-09, with the labels that each got.

#5614 Adding override code to create RestAPI Lambda Authorizers
  src/fragments/lib/restapi/js/authz.mdx
  src/pages/cli/restapi/override.mdx
Labels: amplify/cli, amplify/data, external-contributor, technical-review-needed

#5806 fix(push-notifications): Updated cross platform setup
  cspell.json
  public/images/push-notifications/setup-apns/create-certificate--cert-assistant.png
  public/images/push-notifications/setup-apns/create-certificate--configure.png
  public/images/push-notifications/setup-apns/create-certificate--create.png
  public/images/push-notifications/setup-apns/create-certificate--export-cert.png
  public/images/push-notifications/setup-apns/create-certificate--my-cert.png
  public/images/push-notifications/setup-apns/create-certificate--upload-cert.png
  public/images/push-notifications/setup-apns/create-identifier--add.png
  public/images/push-notifications/setup-apns/create-identifier--app-id.png
  public/images/push-notifications/setup-apns/create-identifier--app-type.png
  public/images/push-notifications/setup-apns/create-identifier--bundle-id.png
  public/images/push-notifications/setup-apns/create-identifier--enable-PN.png
  public/images/push-notifications/setup-fcm/manage-api.png
  public/images/push-notifications/setup-fcm/project-settings.png
  public/images/push-notifications/setup-fcm/server-id.png
  src/fragments/lib/push-notifications/android/setup_push_service/setup-fcm.mdx
  src/fragments/lib/push-notifications/flutter/request_permissions/sample-permissions-flow.mdx
  src/fragments/lib/push-notifications/ios/getting_started/apns-cli-resources.mdx
  src/fragments/lib/push-notifications/ios/setup_push_service/setup-apns.mdx
Labels: amplify/ios, amplify/android, amplify/flutter, react-native

#5851 Fix for Dependabot Alert #57
  jest.setup.js
  package.json
  yarn.lock
Labels: Dependency Update, amplify/docs-engineering

#5861 fix:links to UI docs should be external and open in new window
  src/plugins/internal-link.tsx
Labels: amplify/docs-engineering

#5860 fix: mark SecondaryNav as nav element
  src/components/SecondaryNav/index.tsx
Labels: amplify/docs-engineering

#5757 fix(JS): Add callouts for Push Notifications and Social Sign-in from GH Issues
  src/fragments/lib-v1/auth/android/common_prereq.mdx
  src/fragments/lib-v1/auth/flutter/common_prereq.mdx
  src/fragments/lib/auth/android/common_prereq.mdx
  src/fragments/lib/auth/flutter/common_prereq.mdx
  src/fragments/lib/auth/ios/getting_started/15_preReq_web_ui.mdx
  src/fragments/lib/auth/js/react-native-social.mdx
  src/fragments/lib/auth/js/social.mdx
  src/fragments/lib/push-notifications/android/getting_started/10_pre_req.mdx
Labels: amplify/js, ready-to-merge

#5862 fix: Fix spacing near page title in On this page TOC
  src/components/TableOfContents/styles.tsx
  src/constants/algolia.ts
Labels: amplify/docs-engineering

#5824 update install page prerequisite
  cspell.json
  src/pages/cli/start/install.mdx
Labels: amplify/cli

#5863 fix(bug): Links at the bottom of Contribute page are marked as external so should open in a new tab
  src/pages/contribute/getting-started.tsx
Labels: amplify/docs-engineering

#5867 Putting edit button back on left nav
  src/components/Menu/RepoActions/index.tsx
  src/components/Menu/index.tsx
Labels: amplify/docs-engineering

#5872 fix: making hosting link open in a new tab on the home page
  src/components/Card/styles.tsx
  src/pages/index.tsx
Labels: amplify/docs-engineering

#5869 Fix: Removed identify user feature in the navbar for JS library
  src/directory/directory.mjs
Labels: amplify/docs-engineering

#5797 Hosting: Minor editorial fixes for git-based-deployments.mdx
  src/fragments/guides/hosting/git-based-deployments.mdx
Labels: amplify/hosting, product-owner-review-needed

#5490 AWS Amplify docs adding Amplify Studio which was missing
  src/pages/start/q/integration/[integration].mdx
Labels: first-time-contributor, external-contributor, amplify/studio, product-owner-review-needed

#5881 fix: scroll behavior on left menu
  src/components/Menu/styles.tsx
Labels: amplify/docs-engineering

#5891 Update Amplify Android Versions
  src/constants/versions.ts
Labels: amplify/android, product-owner-review-needed, technical-review-needed

#5899 Adding InlineFragment content
  Readme.md
Labels: amplify/docs-engineering

#5882 GitHub workflow to block PR if new fragments are created
  .github/workflows/check_for_new_fragments.yml
  .github/workflows/scripts/check_for_new_fragments.js
Labels: amplify/docs-engineering

#5823 update custom example to use cdkv2 imports
  src/pages/cli/graphql/custom-business-logic.mdx
Labels: amplify/cli

#5938 fix: broken external links
  src/fragments/lib/auth/js/react-native-social.mdx
  src/fragments/lib/utilities/serviceworker.mdx
Labels: amplify/docs-engineering

#5893 add sitemap location to robots.txt
  tasks/generate-sitemap.mjs
Labels: amplify/docs-engineering

#5945 fix: add trackPageVisit to Pages component
  src/components/Page/index.tsx
  src/utils/track.ts
Labels: amplify/docs-engineering

#5926 Update Readme with fragment update
  Readme.md
Labels: amplify/docs-engineering
