Repository aws-amplify/docs, pull requests merged in 2023-12, with the labels that each got.

#6587 feat(Swift): Adding Storage's Transfer Acceleration page
  src/fragments/lib/storage/android/transfer-acceleration.mdx
  src/fragments/lib/storage/flutter/transfer-acceleration.mdx
  src/fragments/lib/storage/native_common/transfer-acceleration/common.mdx
  src/pages/[platform]/build-a-backend/storage/transfer-acceleration/index.mdx
Labels: amplify/ios

#6551 fix: change background color of search
  src/styles/algolia.scss
Labels: amplify/docs-engineering

#6528 fix: remove external icon after amplify documentation
  src/pages/contribute/getting-started.tsx
Labels: amplify/docs-engineering

#6560 fix: make the amplify hosting card open in new tab
  src/components/Overview/Overview.tsx
Labels: amplify/docs-engineering

#6489 fix: add spacing for each line in callout component
  src/styles/callout.scss
Labels: amplify/docs-engineering

#6562 Remove preloading fonts that weren't being used
  public/fonts/AmazonEmber_W_Lt.woff2
  public/fonts/AmazonEmber_W_Rg.woff2
  src/pages/_document.tsx
  src/styles/font-faces.scss
Labels: amplify/docs-engineering, deleted-assets

#6619 Cbonif/add split schema section
  src/pages/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx
Labels: incorrect-info, API GraphQL

#6617 Add mobile meta viewport
  src/pages/_app.tsx
Labels: amplify/docs-engineering

#6575 Defer shortbread
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: amplify/docs-engineering

#6520 Update type for sample
  src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx
Labels: amplify/js

#6641 docs(graphql-api): callout additional step when adding permission to lambda
  src/pages/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/index.mdx
Labels: amplify/data

#6624 add schema generation and iterative change info to Connect to existing database page
  cspell.json
  src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx
Labels: API GraphQL

#6642 Use canonical url from meta if it exists
  src/data/canonical-urls.ts
  src/pages/_app.tsx
Labels: amplify/docs-engineering

#6662 fix: wrong example provided in amplify analytics version 6
  src/pages/[platform]/build-a-backend/more-features/analytics/record-events/index.mdx
Labels: amplify/js, external-contributor

#6516 fix(gen2): Cognito Auth overrides update
  src/pages/gen2/build-a-backend/auth/enable-sign-up/index.mdx
  src/pages/gen2/build-a-backend/auth/override-cognito/index.mdx
Labels: amplify/auth, amplify/gen2

#6699 chore: font consolidation
  public/fonts/AmazonEmberDisplay_Bd.ttf
  public/fonts/AmazonEmberDisplay_BdIt.ttf
  public/fonts/AmazonEmberDisplay_Rg.ttf
  public/fonts/AmazonEmberDisplay_RgIt.ttf
  public/fonts/AmazonEmberMono_Bd.ttf
  public/fonts/AmazonEmber_Bd.ttf
  public/fonts/Amazon_Ember_Bd.ttf
  public/fonts/Amazon_Ember_BdIt.ttf
  public/fonts/Amazon_Ember_Lt.ttf
  public/fonts/Amazon_Ember_LtIt.ttf
  public/fonts/Amazon_Ember_Rg.ttf
  public/fonts/Amazon_Ember_RgIt.ttf
  public/fonts/Amazon_Ember_Th.ttf
  public/fonts/Amazon_Ember_ThIt.ttf
  src/styles/contribute-styles.scss
  src/styles/font-faces.scss
Labels: deleted-assets

#6602 Remove CSP section from customHttp.yml
  customHttp.yml
  src/pages/_document.tsx
Labels: amplify/docs-engineering

#6717 chore(fonts/css): more font cleanup
  public/fonts/Amazon_Ember_Lt.ttf
  public/fonts/Amazon_Ember_LtIt.ttf
  public/fonts/Amazon_Ember_Th.ttf
  public/fonts/Amazon_Ember_ThIt.ttf
  src/styles/contribute-styles.scss
  src/styles/font-faces.scss
Labels: deleted-assets
