Repository aws-amplify/docs, pull requests merged in 2023-10, with the labels that each got.

#5946 Update cli links
  src/fragments/lib/auth/js/advanced.mdx
  src/pages/cli-legacy/graphql-transformer/auth.mdx
  src/pages/cli-legacy/graphql-transformer/connection.mdx
  src/pages/cli-legacy/graphql-transformer/directives.mdx
  src/pages/cli-legacy/graphql-transformer/key.mdx
  src/pages/cli-legacy/graphql-transformer/overview.mdx
  src/pages/cli-legacy/graphql-transformer/versioned.mdx
  src/pages/cli/migration/lambda-layers-update.mdx
  src/pages/cli/project/permissions-boundary.mdx
  src/pages/cli/project/troubleshooting.mdx
  src/pages/cli/reference/files.mdx
  src/pages/cli/restapi/restapi.mdx
  src/pages/cli/teams/commands.mdx
  src/pages/console/data/data-model.mdx
Labels: amplify/cli, product-owner-review-needed

#5948 Move page view event into Layout component
  src/components/Layout/index.tsx
  src/components/Page/index.tsx
Labels: amplify/docs-engineering

#5958 Add resolution for zod 3.22.3
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5961 Upgrade next to 13.5.4
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5954 remove cloudscape from dependencies
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#5963 Add expander ID to event name
  src/utils/track.ts
Labels: amplify/docs-engineering

#5949 Update build scripts
  amplify.yml
  package.json
Labels: amplify/docs-engineering

#5841 fix typo in condition conjunction
  src/fragments/lib/auth/js/advanced.mdx
Labels: amplify/js, first-time-contributor, external-contributor, ready-to-merge

#5924 Adding custom resource error message when deployed from studio
  src/pages/console/adminui/extend-cli.mdx
Labels: external-contributor, amplify/studio

#5868 chore: update codeowners by product
  .github/CODEOWNERS
Labels: amplify/docs-engineering

#5984 Update links
  generatePathMap.cjs.js
  src/directory/directory.mjs
  src/fragments/lib-v1/graphqlapi/flutter/getting-started/40_codegen.mdx
  src/fragments/start/getting-started/reactnative/nextsteps.mdx
  src/fragments/start/getting-started/vue/nextsteps.mdx
  src/pages/cli/usage/containers.mdx
  src/pages/lib-v1/auth/advanced/q/platform/[platform].mdx
Labels: amplify/docs-engineering

#5987 Update csp
  customHttp.yml
  src/pages/_document.tsx
Labels: amplify/docs-engineering

#5950 Add link checker workflow for PRs
  .github/workflows/check_for_broken_links.yml
  .github/workflows/check_pr_for_broken_links.yml
  generatePathMap.cjs.js
  package.json
  tasks/link-checker.js
  yarn.lock
Labels: amplify/docs-engineering

#5998 chore(flutter): remove null safety references
  src/components/FeatureFlags/feature-flags.json
  src/fragments/lib-v1/datastore/flutter/getting-started/50_codegenCli.mdx
  src/fragments/lib-v1/graphqlapi/flutter/getting-started/40_codegen.mdx
  src/fragments/lib-v1/project-setup/flutter/null-safety/null-safety.mdx
  src/fragments/lib-v1/project-setup/native_common/prereq/flutter_null_safety.mdx
  src/fragments/lib/project-setup/native_common/prereq/flutter_null_safety.mdx
  src/pages/lib-v1/project-setup/null-safety/q/platform/[platform].mdx
Labels: redirects-needed

#6007 Update-project-setup
  src/pages/lib-v1/project-setup/create-application/q/platform/[platform].mdx
Labels: amplify/js

#6006 Add custom analytics event for the "What's New" banner
  src/components/WhatsNewBanner/index.tsx
  src/utils/track.ts
Labels: amplify/docs-engineering

#5939 Auth: Copyedit of guide for sign-in, sign-up, and sign-out
  src/pages/lib/auth/emailpassword/q/platform/[platform].mdx
Labels: amplify/js, product-owner-review-needed, react-native, technical-review-needed

#6031 Revert "Update CODEOWNERS to exclude documentation team from all files"
  .github/CODEOWNERS
Labels: amplify/docs-engineering

#5874 chore: update sample amplifyconfiguration json file
  src/fragments/lib/auth/android/getting_started/50_configureBackend.mdx
  src/fragments/lib/auth/ios/getting_started/50_configureBackend.mdx
Labels: amplify/ios, amplify/android, product-owner-review-needed, ready-to-merge

#5995 Add new menu
  src/components/FilterChildren/__tests__/FilterChildren.test.tsx
  src/components/Icons/IconExternalLink.tsx
  src/components/Icons/index.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/LayoutProvider.tsx
  src/components/Layout/index.ts
  src/components/Menu/Directory/__tests__/Directory.test.tsx
  src/components/Menu/Directory/index.tsx
  src/components/Menu/Directory/styles.tsx
  src/components/Menu/FilterSelect/__tests__/FilterSelect.test.tsx
  src/components/Menu/FilterSelect/index.tsx
  src/components/Menu/FilterSelect/styles.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuCloseButton/__tests__/MenuCloseButton.test.tsx
  src/components/Menu/MenuCloseButton/index.tsx
  src/components/Menu/MenuCloseButton/styles.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Menu/MenuOpenButton/__tests__/MenuOpenButton.test.tsx
  src/components/Menu/MenuOpenButton/index.tsx
  src/components/Menu/MenuOpenButton/styles.tsx
  src/components/Menu/RepoActions/index.tsx
  src/components/Menu/RepoActions/styles.tsx
  src/components/Menu/VersionSwitcher/index.tsx
  src/components/Menu/VersionSwitcher/styles.tsx
  src/components/Menu/__tests__/Menu.test.tsx
  src/components/Menu/index.ts
  src/components/Menu/index.tsx
  src/components/Menu/styles.tsx
  src/data/platforms.ts
  src/directory/directory.d.ts
  src/directory/directory.mjs
  src/pages/[platform]/build-a-ui/index.mdx
  src/styles/layout.scss
  src/styles/menu.scss
  src/styles/styles.scss
  src/utils/getLocalDirectory.test.ts
  tasks/generate-sitemap.mjs
Labels: amplify/docs-engineering

#6041 Remove unnecessary router.isReady check
  src/components/Layout/Layout.tsx
Labels: amplify/docs-engineering

#5981 fix(storage): update 'guest' to `guest` in update api
  src/directory/directory.mjs
  src/pages/lib-v1/storage/upload/q/platform/[platform].mdx
Labels: product-owner-review-needed

#6053 Add script to generate directory object
  .gitignore
  package.json
  src/components/Layout/Layout.tsx
  src/directory/directory.d.ts
  src/directory/directory.mjs
  src/directory/generateDirectory.mjs
  src/pages/[platform]/build-a-backend/api-graphql/index.mdx
  src/pages/[platform]/build-a-backend/api-rest/index.mdx
  src/pages/[platform]/build-a-backend/index.mdx
  src/pages/[platform]/build-a-ui/index.mdx
  src/pages/[platform]/get-started/index.mdx
  src/pages/[platform]/get-started/project-setup/index.mdx
  src/pages/[platform]/get-started/sample-apps/index.mdx
  src/pages/[platform]/get-started/tutorials/connect-api-and-database.mdx
  src/pages/[platform]/get-started/tutorials/deploy-and-host-app.mdx
  src/pages/[platform]/get-started/tutorials/index.mdx
  src/pages/[platform]/get-started/tutorials/next-steps.mdx
  src/pages/[platform]/get-started/tutorials/setup-amplify.mdx
  src/pages/[platform]/get-started/tutorials/setup-fullstack-project.mdx
  src/pages/[platform]/index.tsx
  src/pages/[platform]/test-page/index.mdx
  yarn.lock
Labels: amplify/docs-engineering

#5936 docs (js): Copyedited "Set up Amplify Auth" guide
  src/pages/lib/auth/getting-started/q/platform/[platform].mdx
Labels: amplify/js, product-owner-review-needed, technical-review-needed

#6077 Set isExternal to true for whats new banner
  src/components/WhatsNewBanner/index.tsx
Labels: amplify/docs-engineering

#6075 Add page overview component to display child pages as cards
  mdx-components.tsx
  src/components/Overview/Overview.tsx
  src/components/Overview/index.ts
  src/pages/[platform]/build-a-backend/index.mdx
  src/pages/[platform]/get-started/tutorials/connect-api-and-database.mdx
  src/pages/[platform]/get-started/tutorials/index.mdx
  src/styles/layout.scss
  src/styles/overview.scss
  src/styles/styles.scss
  src/utils/getChildPageNodes.ts
Labels: amplify/docs-engineering

#6095 Update next config
  next.config.mjs
  package.json
  yarn.lock
Labels: amplify/docs-engineering

#6051 add standalone how amplify works page
  public/images/how-amplify-works/amplify-flow.png
  public/images/how-amplify-works/amplify-scenarios.png
  public/images/how-amplify-works/checkmark.png
  public/images/how-amplify-works/figma-to-code.png
  public/images/how-amplify-works/hosting-deployed-site.png
  public/images/how-amplify-works/hosting-form.png
  public/images/how-amplify-works/ui-library-form-builder.png
  public/images/how-amplify-works/ui-library-primitive-components.png
  public/images/how-amplify-works/ui-library-sign-in.png
  src/components/SecondaryNav/index.tsx
  src/directory/directory.mjs
  src/pages/how-amplify-works.mdx
  yarn.lock
Labels: amplify/docs-engineering

#6110 Update how we display page last updated
  .gitignore
  amplify.yml
  next.config.mjs
  package.json
  src/components/Fragments/index.tsx
  src/components/LastUpdatedProvider/index.tsx
  src/components/Layout/Layout.tsx
  src/components/PageLastUpdated/PageLastUpdated.tsx
  src/components/PageLastUpdated/index.ts
  src/directory/directory.d.ts
  src/directory/generateDirectory.mjs
  src/directory/generateFlatDirectory.mjs
  src/pages/[platform]/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/plugins/frontmatter.tsx
  src/styles/layout.scss
  src/styles/page-last-updated.scss
  src/styles/styles.scss
  tasks/addLastUpdatedToMdxFiles.js
Labels: amplify/docs-engineering
