Repository aws-amplify/docs, pull requests merged in 2024-05, with the labels that each got.

#6471 re add action to check for console errors
  .github/CODEOWNERS
  .github/workflows/check_for_console_errors.yml
  cspell.json
  public/images/console/7_authreadonly.png
  src/components/BlockSwitcher/__tests__/BlockSwitcher.test.tsx
  src/pages/[platform]/tools/console/authz/permissions/index.mdx
  tasks/console-errors.js
  tasks/get-sitemap-links.js
Labels: amplify/docs-engineering

#7496 restructured the contents for connecting to existing data sources
  cspell.json
  src/directory/directory.mjs
  src/pages/[platform]/build-a-backend/data/connect-existing-data/index.mdx
  src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-external-ddb-table/index.mdx
  src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/index.mdx
  src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/index.mdx
  src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-bedrock/index.mdx
  src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-eventbridge-datasource/index.mdx
  src/pages/[platform]/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/index.mdx
  src/pages/[platform]/build-a-backend/data/data-modeling/add-fields/index.mdx
  yarn.lock
Labels: redirects-needed

#7514 Remove empty/unused page
  src/pages/[platform]/build-a-backend/data/offline/index.mdx
Labels: redirects-needed

#7626 update mobile icons and remove unused icons
  public/assets/icon/android-icon-144x144.png
  public/assets/icon/android-icon-192x192.png
  public/assets/icon/android-icon-36x36.png
  public/assets/icon/android-icon-48x48.png
  public/assets/icon/android-icon-72x72.png
  public/assets/icon/android-icon-96x96.png
  public/assets/icon/apple-icon-114x114.png
  public/assets/icon/apple-icon-120x120.png
  public/assets/icon/apple-icon-144x144.png
  public/assets/icon/apple-icon-152x152.png
  public/assets/icon/apple-icon-180x180.png
  public/assets/icon/apple-icon-57x57.png
  public/assets/icon/apple-icon-60x60.png
  public/assets/icon/apple-icon-72x72.png
  public/assets/icon/apple-icon-76x76.png
  public/assets/icon/apple-icon-precomposed.png
  public/assets/icon/apple-icon.png
  public/assets/icon/ms-icon-144x144.png
  public/assets/icon/ms-icon-150x150.png
  public/assets/icon/ms-icon-310x310.png
  public/assets/icon/ms-icon-70x70.png
Labels: deleted-assets
