Repository aws-amplify/docs, pull requests merged in 2024-08, with the labels that each got.

#7814 adds storage, user and data management pages
  public/images/gen2/manage/data-manager.mp4
  public/images/gen2/manage/storage-manager.mp4
  public/images/gen2/manage/user-manager.mp4
  src/directory/directory.mjs
  src/pages/[platform]/build-a-backend/auth/manage-users/with-amplify-console/index.mdx
  src/pages/[platform]/build-a-backend/data/manage-with-amplify-console/index.mdx
  src/pages/[platform]/build-a-backend/storage/manage-with-amplify-console/index.mdx
  src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
Labels: amplify/gen2

#7878 add non-dev mode info to figma to react docs
  src/pages/[platform]/build-ui/figma-to-code/index.mdx
Labels: amplify/gen2

#7806 rework "use existing cognito resources" prose, highlight configuring client libs directly
  src/directory/directory.mjs
  src/pages/[platform]/build-a-backend/auth/use-existing-cognito-resources/index.mdx
  src/pages/[platform]/start/connect-existing-aws-resources/index.mdx
  src/pages/[platform]/start/connect-to-aws-resources/index.mdx
Labels: redirects-needed

#7737 Feat (Auth): added docs for fetchCurrentDevice API
  src/pages/[platform]/build-a-backend/auth/manage-users/manage-devices/index.mdx
Labels: do-not-merge
